### ISSUE TITLE
Add the option for embedded notifications

### ISSUE THREAD

**Issue by zeroquinc** [pajlads/DinkPlugin#105]
I use this plugin because it's by far the most complete out of all and imo the least buggy.

But one thing I would like to get added is the option for embedded notifications. In my opinion they are better to read and look less cluttered than non embedded messages. I use this plugin for every notification in the game possible, instead for loot. For that I use an other plugin so it looks like this:

![image](https://user-images.githubusercontent.com/39315068/209372339-ffc6478b-e834-4bba-b5c0-53801ec5a1d0.png)

Is it possible for Dink to also have an option for embedded notifications? I know this is a personal preference and probably for a lot a people not a must-have, but I wanted to know what u thought about it.

Happy holidays!

**Comment by Felanbird** [comment]
Embedding obviously looks like a much better approach, we just never took any steps towards it previously as we(the members of this repo) don't use discord for our notifications.
