### ISSUE TITLE
Only Send Death Notification on PvP Death

### ISSUE THREAD

**Issue by jdanthdavis** [pajlads/DinkPlugin#116]
It's awesome that we can send two different messages for PvM death and PvP death but would it be possible to have an option to only send a notification on PvP death only?

**Comment by iProdigy** [comment]
Thanks for the request, there are still some edge cases where the death notifier may classify some PK deaths as PvM, so I would not want to implement this setting until we sort out more of those edge cases

**Comment by iProdigy** [comment]
Not quite what you requested but #166 will help reduce spam from death notifications (if configured appropriately)

**Comment by AFKLgnd** [comment]
Wanted to post here since it's along the same line of thought instead of opening a new issue - Option to not send notifications if death is in house. Unneeded posts if afking with venom or something similar.

**Comment by pajlada** [comment]
> Wanted to post here since it's along the same line of thought instead of opening a new issue - Option to not send notifications if death is in house. Unneeded posts if afking with venom or something similar.

The version of Dink that's on the plugin hub right now shouldn't send deaths from your PoH, have you confirmed deaths in your house are sent?

**Comment by AFKLgnd** [comment]
[In house with Dink settings](https://i.imgur.com/meaAhEq.jpeg)

[Discord notification](https://i.imgur.com/PhcGiDy.png)

**Comment by iProdigy** [comment]
@AFKLgnd Thanks for the bug report, this regression was introduced in v1.3.2, will write the fix now.

**Comment by iProdigy** [comment]
@AFKLgnd Thanks for the bug report - we have identified the cause and are writing a fix now.
