### ISSUE TITLE
Setting to skip virtual levels

### ISSUE THREAD

**Issue by pajlada** [pajlads/DinkPlugin#121]
I would like a setting to disable notifications for virtual levels (i.e. I only want notifications for levels 1-99).
This should probably be a simple checkbox, where the default value should 

Discussion points:
Should it be a positive checkbox? "Notify for virtual levels" where true would be default
Should it be a negative checkbox? "Skip virtual levels" where false would be default

**Comment by Felanbird** [comment]
I'd prefer using a positive checkbox, as the default runelite plugin `XP Globes` uses a positive checkbox. 
`but we have to pluralize our setting`

https://github.com/runelite/runelite/blob/9b655588e6da6b6489021d6b30f6b1d328c17dd4/runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesConfig.java#L103-L112
```
	@ConfigItem(
		keyName = "showVirtualLevel",
		name = "Show virtual level",
		description = "Shows virtual level if over 99 in a skill and Hide maxed skill is not checked",
		position = 15
	)
	default boolean showVirtualLevel()
	{
		return false;
	}
```
