### ISSUE TITLE
Always send uniques

### ISSUE THREAD

**Issue by zeroquinc** [pajlads/DinkPlugin#130]
First of all thanks very much for the embed commit, my notifications look so much cleaner now!

A feature I still would like to see added is an option under Loot; Always send uniques.

The way it works now is that the collection log notification will still pop but if you already have gotten it once it obviously won't. 

Could this be a new toggle? Thank you it's very nice to see active development on this!

**Comment by Felanbird** [comment]
My immediate question is how do we go about checking what is a unique? 
From what I can see `discord-rare-drop-notifier` has their own list but taking that approach would be no fun. https://github.com/BossHuso/discord-rare-drop-notificater/blob/master/src/main/java/com/masterkenth/EventRarity.java 

Hopefully there's some API that we could use to figure this out 🤔

**Comment by pajlada** [comment]
By unique, do you mean every item in the collection log? So if this setting is on, you'd send a loot notification every time you loot a:
 - Vorkath's head from Vorkath
 - Soaked pages from Tempoross
 - Ancient Shard from any monster in Catacombs of Kourend
 - Ancient essence from Phantom Muspah
 - Iasor/Kronos/Attas seed from Hespori
 - Granite dust from Grotesque Guardians
 - Mole skin or Mole claw from Giant Mole
 - Bolt rack from Barrows

**Comment by zeroquinc** [comment]
Yeah, that is kinda what I meant. And then for example that you can set a minimum value and drop rate. 

For example I don't want to have every Mole claw as notification but if I could set the value rarity to have a minimum of 1/256 it would still give me notifications for rare drops that maybe cost less than what I have set up under "Loot" as `Min Loot Value`.

**Comment by pajlada** [comment]
Do you think your recent suggestion of https://github.com/pajlads/DinkPlugin/issues/139 would cover this use-case effectively?

**Comment by zeroquinc** [comment]
> Do you think your recent suggestion of #139 would cover this use-case effectively?

Yeah, I think it does. Maybe it's better to close this and continue in that topic.
