### ISSUE TITLE
Option to let the Loot notifier ignore Clue drops?

### ISSUE THREAD

**Issue by TomBolks** [pajlads/DinkPlugin#133]
It would be nice to prevent duplicate clue notifications. They way I did it on UniversalDiscordPlugin: https://github.com/TomBolks/UniversalDiscordNotifier/commit/6da978c1f7ba73afc44999134577f109df5f7c73#diff-ddb861fd31a9f9e62e73b89e9b9a6d24439ff3a173130e6829c997f9a016b121R46
Always ignoring all loot from clue's.

But now I think a checkbox in the config would be a bit nicer.

![image](https://user-images.githubusercontent.com/17124771/213288962-1881e624-bb3b-4b61-b0d7-4b0b8af5a8c4.png)

**Comment by iProdigy** [comment]
I'd agree with a default-off checkbox for this to preserve old behavior as some users have separate discord channels for loot/clue & *do* want the duplication

**Comment by iProdigy** [comment]
@TomBolks did you want to take this PR or are you busy until the weekend?

**Comment by pajlada** [comment]
This can now be configured wit the "Include Clue Loot" checkbox under the "Loot" category. This is checked by default to be consistent with the behaviour previous to this change.
![image](https://user-images.githubusercontent.com/962989/213412331-a61cbd60-8366-4e33-a4eb-89a012214c66.png)
