### ISSUE TITLE
Collection Log - Item picture in embed notification

### ISSUE THREAD

**Issue by zeroquinc** [pajlads/DinkPlugin#140]
Sorry if I'm opening to many issues but me and my friends love this plugin and we still think we have some good idea's to add to this plugin.

Would it be possible to put a picture of the item in the collection log embedded message?

If i remember correctly embedded messages can include up to 4 images. 
Would be great if this could be toggled so that I could disable screenshots and include item pictures.

Thanks in advance!

**Comment by Felanbird** [comment]
Already added in #128 

Will be available in 1.2.1 runelite/plugin-hub/pull/3798

**Comment by zeroquinc** [comment]
Great, sorry I missed that.
