### ISSUE TITLE
Dink not posting notifications to Discord when RSN contains a space

### ISSUE THREAD

**Issue by CypherNL** [pajlads/DinkPlugin#142]
**Dink version:** 1.2.1

Since version 1.2.1 our Discord channel doesn't get notifications anymore. So far it's with the loot and the achievements webhook.

The settings seems to be the same as in version 1.2.0. So i believe the webhook overrides stopped working.
The lost notifications were also not posted on the main webhook. So i believe the plugin still uses the webhook override but something did go wrong after that.

A different member of the Discord group I'm in also has this problem where his notifications weren't posted into Discord. So it's not a problem that's related to my RuneLite setup.

**Comment by Felanbird** [comment]
I'm currently and have been using the jar equivalent to `1.2.1` release since the day we opened the plugin-hub PR - so if there is an issue it's somehow an issue with the launcher version.
![image](https://user-images.githubusercontent.com/41973452/214965207-89fe28d6-9d41-41ce-ac69-a7ff5143179a.png)


I'll take a look once I finish this Kraken instance

**Comment by CypherNL** [comment]
I also just removed the webhook overrides. Even then the plugin doesn't post anything. So it's not a webhook override issue.

**Comment by pajlada** [comment]
Can you verify that your webhook URL is still alive? The RuneLite client.log would contain info if there's a network issue at least

**Comment by Felanbird** [comment]
Here's a tool for quick webhook testing if you don't have the means to do it yourself https://lew.la/discord/webhook-tester

**Comment by CypherNL** [comment]
The Webhook URL is alive, i had even copied from the webhooks interface and pasted into Dink to be sure if the link is correct.

In the log there's this issue posted a couple of times:
```
2023-01-26 23:35:01 [pool-3-thread-1] WARN  d.message.DiscordMessageHandler - Exhausted retry attempts when sending the webhook message
java.lang.RuntimeException: Received unsuccessful http response: 400 -  - {"embeds": ["0"]}
	at dinkplugin.message.DiscordMessageHandler.lambda$sendMessage$4(DiscordMessageHandler.java:137)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by CypherNL** [comment]
> Here's a tool for quick webhook testing if you don't have the means to do it yourself https://lew.la/discord/webhook-tester

I got the error "Error sending webhook message" on that website. Wierd. Could Discord having issues with webhooks?

**Comment by Felanbird** [comment]
> > Here's a tool for quick webhook testing if you don't have the means to do it yourself [lew.la/discord/webhook-tester](https://lew.la/discord/webhook-tester)
> 
> I got the error "Error sending webhook message" on that website. Wierd. Could Discord having issues with webhooks? **EDIT:** Got the same error using a fresh new webhook.

Apparently lew.la's webhook tool doesn't work anymore 💤 



Are you using a custom footer for your notifs?

**Comment by CypherNL** [comment]
Nope. Just the standard Dink footer.

**Comment by Felanbird** [comment]
Can you try disabling `Use Rich Embeds` and see if you at least get the old ugly notifs? While we try to figure out why this is happening
![image](https://user-images.githubusercontent.com/41973452/214967447-a07a137c-0fb8-4db5-833e-a07805c9985d.png)

**Comment by CypherNL** [comment]
Disabling `Use Rich Embeds` did work. It posted a loot notification.
![Old notification works](https://user-images.githubusercontent.com/11279045/214968024-84ea6a2b-8ac9-42df-946e-d944e36d4d84.png)

**Comment by Felanbird** [comment]
Do you or your friends have spaces in your usernames? Nobody we would have tested with does. (just softballing ideas)

**Comment by Felanbird** [comment]
Also, try re-enabling `Use Rich Embeds` but set `Player Lookup Service` to `None` (the very last setting in advanced)

**Comment by CypherNL** [comment]
Yes. We all use a space in the name since we use a couple of capitals as our GIM group name.

**Comment by Felanbird** [comment]
> Yes. We all use a space in the name since we use a couple of capitals as our GIM group name.

Ah that's probably it then xd

**Comment by CypherNL** [comment]
> Also, try re-enabling `Use Rich Embeds` but set `Player Lookup Service` to `None` (the very last setting in advanced)

Worked!
![New notification works without highscores](https://user-images.githubusercontent.com/11279045/214968657-909de2a8-7d30-4753-9238-a0674abb5d65.png)

**Comment by Felanbird** [comment]
> > Also, try re-enabling `Use Rich Embeds` but set `Player Lookup Service` to `None` (the very last setting in advanced)
> 
> Worked

Yeah so it's just because we didn't think to `urlencode` the hiscore links, we'll fix that as soon as possible 🙂

**Comment by Felanbird** [comment]
@CypherNL Fix is merged released and commited to plugin-hub (thanks to nightfirecat), so the issue will be resolved as soon as you restart (+however long it takes for updates to reach the user, 5 minutes? idk)

**Comment by pajlada** [comment]
Thanks for the detailed report & help with debugging @CypherNL !

**Comment by CypherNL** [comment]
Problem is fixed. Thanks everyone!

**Comment by CypherNL** [comment]
> Thanks for the detailed report & help with debugging @CypherNL !

No problem. Thanks for the quick fix!
