### ISSUE TITLE
New notifier: Barbarian Assault high level gambles

### ISSUE THREAD

**Issue by equirs** [pajlads/DinkPlugin#145]
Hi from Casual BA! I've noticed that this plugin supports a bunch of neat webhooks and was interested in the possibility of automatically sending players' high gamble counts to our Discord, since we have a channel for players to submit these manually. Gambles are a big deal in our community as we use it to determine ranks, maintain our own unofficial hiscores, and award discord badges for certain milestones. If this feature is deemed appropriate for this plugin, I'd be down to implement it.

**Comment by pajlada** [comment]
Hi! Thank you for reaching out.
We think this fits well into the plugin, and think it should be its own new notifier. :+1: 
Feel free to use this issue if you have any questions for how to get started or if you run into any issues!

**Comment by iProdigy** [comment]
Would be happy to accept this as a new notifier! Perhaps `GambleNotifier` is a good class/short name

In terms of the logic, it appears this notifier will require widget parsing... you may benefit from checking out the example of unsired handling in `LootNotifier`. Hopefully `Widget#getItemQuantity` reports accurate numbers for barbarian assault (unlike unsired) - if not, you'd have to parse the quantity from the widget text.

As pajlada stated, please feel free to reach out for any assistance. Also, don't feel pressured to also write the corresponding mocked unit tests (we can handle this for you).

**Comment by pajlada** [comment]
I think high gambles produce a chat message now @iProdigy since ~1-2 months which makes this a loooot easier to implement, but equirs would know for sure :D

**Comment by iProdigy** [comment]
Oh, would be nice to avoid widget if chat has all the data we want (item name, item quantity, gamble level, gamble count) as we can translate item name to id via `ItemSearcher`

**Comment by equirs** [comment]
I believe the chat message does have all of that info, so there should be no need to do anything with the widget. We don't particularly care much about the loot, but the message data might as well include it since it's there and it's easy to work in, given the other notifiers handle it.

> Also, don't feel pressured to also write the corresponding mocked unit tests (we can handle this for you).

I don't usually write tests in my own plugins out of laziness, but I'm familiar with Mockito and have seen the other tests in the project. Should be simple enough for me to write some.
