### ISSUE TITLE
400 Abyssal heads from Unsired

### ISSUE THREAD

**Issue by Newbcake** [pajlads/DinkPlugin#146]
I looted an unsired and dink claimed I had looted 400x Abyssal head, I didn't lag at the time or anything.

![Discord_2023-01-27_21-29-47](https://user-images.githubusercontent.com/9064744/215190982-713bfb17-7207-44ef-bf7a-f7a4f5cc34ae.png)

**Comment by Felanbird** [comment]
unlucky

**Comment by iProdigy** [comment]
This was caused by an upstream bug, but will be resolved in the next Dink version.
