### ISSUE TITLE
Pet: Add completions/XP from Clan chat to Dink notification

### ISSUE THREAD

**Issue by CypherNL** [pajlads/DinkPlugin#168]
**Dink version:** 1.3.0

Since the pet notifications now show up with a name. I wonder if it's possible to add the completion / XP section from the GIM / Clan chat notification to the Dink notification?

What the notification now looks like:
![Dink pet notification without KC](https://user-images.githubusercontent.com/11279045/218856837-2642a3da-942c-430a-ad12-d1867ff69cd6.png)

The GIM / Clan chat notification:
![Notification Pet Youngleff](https://user-images.githubusercontent.com/11279045/218856790-fa4fc509-4a91-470f-abdf-460c7b07d418.png)

**Comment by Felanbird** [comment]
pajlada generated a few examples here: https://github.com/pajlads/DinkPlugin/pull/149#issuecomment-1408320489

Might be a bit of a pain to get the full list tho since a bunch of bosses seem to have the messages follow a pattern similar to their activity `e.g. Herbi at 3,054 harvest count`
