### ISSUE TITLE
Add Total Collection Logs to Collection Log Notification

### ISSUE THREAD

**Issue by jdanthdavis** [pajlads/DinkPlugin#173]
Add an additional checkbox in the Collection Log menu for "Total Collection Logs". Having this check will also post the player's total collection log slots in the notification.

Example of Discord notification:
User has added a new item to their collection log: Trident of the seas (full) (701/1443)

Example of the message in-game:
![image](https://user-images.githubusercontent.com/87504521/220497959-50e97f69-fd57-4903-8931-7fdbd7b4f9e6.png)

**Comment by iProdigy** [comment]
Thanks for the feature request. We will incorporate this as a field in the rich embed that is always enabled (no config setting). We're also able to accomplish this with a more robust approach than that of the collection log plugin pictured above by utilizing undocumented VarPlayer id's.
