### ISSUE TITLE
Add an allowlist instead of only a denylist

### ISSUE THREAD

**Issue by WhatTheHai** [pajlads/DinkPlugin#177]
For my use case it's pretty unhandy for me to add all my alts, rather i'd like to only allow two accounts to an allowlist to send webhook messages from

**Comment by Felanbird** [comment]
When this feature was originally requested it was requested as an allowlist, we had a discussion about this during said implementation, and we came to the conclusion that a denylist was generally better than an allowlist.

When it comes to the actual functionality of said list, when you input a name into the denylist, you lose the functionality for that single account, but when you add an account to the allowlist, you lose functionality for all accounts ever, except that account.

In your use-case it's unfortunately inconvenient to denylist a bunch of accounts, but we believe in the long-run it prevents confusion to the user to only offer a denylist.
