### ISSUE TITLE
Death notifier doesn't distinguish PvP deaths at LMS properly

### ISSUE THREAD

**Issue by Mm2PL** [pajlads/DinkPlugin#186]
If you die at Last Man Standing, the death notification will be a normal one as if you died to a monster, not another player.
![Scriptorex message with me dying](https://user-images.githubusercontent.com/25011746/222925124-14f508f9-2a0a-49d5-b5ed-ca8904e2e579.png)

![Dying on my HCIM: completed](https://i.ivr.fi/runelite/9d87ef17a950.png)

**Comment by iProdigy** [comment]
Caused by https://github.com/pajlads/DinkPlugin/blob/master/src/main/java/dinkplugin/notifiers/DeathNotifier.java#L179 - will fix shortly
