### ISSUE TITLE
As a JSON/extra consumer I would like to see the name of the 'killing' monster on death events

### ISSUE THREAD

**Issue by APKiwi** [pajlads/DinkPlugin#189]
Is it possible to capture/emit the name of the event or monster which killed the user similar to how the pvp username is emitted on death?

**Comment by pajlada** [comment]
It's definitely possible, yes. I imagine we'd need to do the same type of guessing we do for NPCs but it should be a bit simpler.

**Comment by APKiwi** [comment]
Legends.
