### ISSUE TITLE
Pet: No XP milestone when getting skilling pet

### ISSUE THREAD

**Issue by CypherNL** [pajlads/DinkPlugin#192]
**Dink version:** 1.3.1

Just got my first skilling pet and yet the plugin didn't posted the milestone (at xxx XP). The milestone did get posted in the GIM chat.
![No milestone skilling pet](https://user-images.githubusercontent.com/11279045/226682020-2cf99976-8bab-4530-8b0b-804db8e71955.png)

![GIM chat message](https://user-images.githubusercontent.com/11279045/226680744-15050d0d-8ab9-4f98-9528-05b512d35f80.png)
From the screenshot the plugin didn't waited for the GIM message.

[Code snippet was here about client log but that was from a different plugin]

**Comment by Felanbird** [comment]
That's not our log btw, that's a lot from `Discord Rare Drop Notificater`, hence the name in the message.

**Comment by pajlada** [comment]
@CypherNL Could you post the full screenshots (censoring username is fine)?

**Comment by CypherNL** [comment]
![Pet 2023-03-21_17-28-28](https://user-images.githubusercontent.com/11279045/226699687-74976171-5437-40e0-8cb5-be98049e0195.png)
I only got this one, i haven't screenshotted it with the GIM clan chat message. Only screenshotted the message and closed the client once since...

The Dink plugin and the rare drop notifier plugin has the same screenshot sadly.

**Comment by Felanbird** [comment]
For the future do you mind adding `:ss` to timestamps? It can be useful for pinpointing this sort of thing, but obviously you didn't know that before this happened.

![image](https://user-images.githubusercontent.com/41973452/226701679-a18539e5-8abf-41cd-aa8f-ca10f0454988.png)

**Comment by CypherNL** [comment]
Yes i will do.

**Comment by CypherNL** [comment]
There was definitely a delay between the collection log / funny feeling message. I think about 1.5/2 seconds.

**Comment by iProdigy** [comment]
Thanks, the current implementation assumes the GIM message occurs on the same tick. I will change this to wait up to 5 ticks

**Comment by pajlada** [comment]
With iProdigy's fix, we will now wait a bit longer when receiving a pet to try to wait for the delayed GIM message.
The fix will be available in the next pluginhub release.

**Comment by CypherNL** [comment]
Just got a different skilling pet, the message to the GIM chat came only 1 second later and the milestone was posted with the pet notification. Also the screenshot was taken 1 second later than the collection log post. So it works!
