### ISSUE TITLE
Distinguish between killing/pickpocketing/misc

### ISSUE THREAD

**Issue by APKiwi** [pajlads/DinkPlugin#195]
Currently no data is passed around if the loot was acquired via a kill, a pickpocket, or other miscellaneous acquisition.

Is it possible to include this additional information in "extra"?

**Comment by pajlada** [comment]
See the JSON blob in the readme under the Loot category https://github.com/pajlads/DinkPlugin#loot - this will be available in the next pluginhub release

**Comment by APKiwi** [comment]
Legends!

**Comment by pajlada** [comment]
They're on different schedule - we'll be making a pull request to publish a new release today but it can take some time for the volunteers to review the change before it gets published

**Comment by iProdigy** [comment]
You can monitor the status of the pluginhub release at https://togithub.com/runelite/plugin-hub/pull/4124
