### ISSUE TITLE
Add extra data to Pet notificiations

### ISSUE THREAD

**Issue by pajlada** [pajlads/DinkPlugin#20]
Right now when you receive a pet and a notification is fired, the extra field is left empty. We should be able to fill this out with the pet name

**Comment by Mm2PL** [comment]
How could we know which pet the user got? Currently we use the chat message to see when the user got something:
```java
private static final Pattern PET_REGEX = Pattern.compile("You have a funny feeling like you.*");
```

**Comment by Felanbird** [comment]
I assume the only way we could do it is if we could somehow check where the user is in game. 
Only the skilling pets can be obtained "anywhere", while every other pet is obtained at a set location.

**Comment by pajlada** [comment]
> How could we know which pet the user got? Currently we use the chat message to see when the user got something:

aaaaaaah, I thought this was part of the message so maybe this is unfeasible :thinking: 

It should really only be added if we can know the pet that was obtained without a doubt

**Comment by pajlada** [comment]
Closing this as it seems it would be unfeasible to implement
