### ISSUE TITLE
Total Completed Entries for Collection Log is Missing

### ISSUE THREAD

**Issue by jdanthdavis** [pajlads/DinkPlugin#201]
#174 implemented the total completed entries for the collection log but they do not appear in the rich embed messages.
![image](https://user-images.githubusercontent.com/87504521/228437368-a82e9cbb-ac7c-46e9-bcf3-9cbfe14c4da6.png)

![image](https://user-images.githubusercontent.com/87504521/228439791-ca6ff3c6-cb9f-4cbd-8454-ec68b1dfa1aa.png)
![image](https://user-images.githubusercontent.com/87504521/228439824-3ae65b3e-ebe2-4ffa-acea-5a97d7f7cc41.png)

**Comment by iProdigy** [comment]
Same explanation as https://github.com/pajlads/DinkPlugin/issues/190#issuecomment-1475084013 - #174 is part of https://github.com/pajlads/DinkPlugin/releases/tag/v1.3.2, which has not been approved into the plugin hub by RuneLite yet: https://togithub.com/runelite/plugin-hub/pull/4124

**Comment by jdanthdavis** [comment]
I see! Thanks for the rapid response!
