### ISSUE TITLE
Hazeel cult parital completion triggers a quest event

### ISSUE THREAD

**Issue by APKiwi** [pajlads/DinkPlugin#204]
When siding with Ceril on the quest 'Hazeel Cult' the partial completion mid way through the quest triggers a quest notification.

`Extra: { questName: 'Hazeel Cult partial completion' }`

Easy enough to filter out server side, but may be worth filtering client side for others.

**Comment by pajlada** [comment]
Interesting find!

I'll mark it as a bug for now, shouldn't be too complicated to have a list of quest names we ignore.
