### ISSUE TITLE
Remove Player Lookup Service Username When None is Selected

### ISSUE THREAD

**Issue by jdanthdavis** [pajlads/DinkPlugin#205]
Some users may not want to have the Player Lookup Service showing in their rich embed format and utilize %USERNAME% in their messages instead. Perhaps, a bit niche scenario but a "Hide" or change the way the "None" option works to completely remove the username from the rich embed would be a nice feature.

![image](https://user-images.githubusercontent.com/87504521/229379259-1a0fc967-ba31-443e-8983-6286ff42175f.png)

_Current message when set to **None**_
![image](https://user-images.githubusercontent.com/87504521/229379274-b25d4f39-adff-400e-bb2a-2c2dda62d11f.png)

_Suggestion_
Maybe even inline whatever icon is used for that particular message with "Collection Log" or "Loot" ect.
![image](https://user-images.githubusercontent.com/87504521/229379302-17f86fbf-7de0-4eb7-822b-7972bf447518.png)

**Comment by iProdigy** [comment]
Could you please elaborate on the use case for this change? That is, *why* would this be helpful / what are you trying to achieve

**Comment by iProdigy** [comment]
Closing this until there is a compelling use case presented
