### ISSUE TITLE
Addition of test events

### ISSUE THREAD

**Issue by APKiwi** [pajlads/DinkPlugin#213]
Would you consider adding a `::dinktest pet` `::dinktest collectionLog` etc to test embeds/notifications and for us extra consumers test events to our servers.

This avoids the problem of attempting to go levelup, get xyz drop, get a pet (drops are easy setting low thresholds, levels harder in most cases, pets...).

**Comment by iProdigy** [comment]
We'll consider this feature...

In the meantime, you can have test messages sent to your server by running our test suite with the `TEST_WEBHOOK_URL` environmental variable pointed at your server. (this also allows you to just run individual tests & have the notification sent to your server)

**Comment by pajlada** [comment]
I think given the flexibility of what you might want to test (various level thresholds etc), running the test suite is going to be the best approach. If there are any tests that's missing in the test suite, we can very easily add them.

**Comment by APKiwi** [comment]
Awesome, I'll give that a go, cheers!

**Comment by iProdigy** [comment]
@APKiwi Was the gradle test suite sufficient for validating your metadata consumer?

**Comment by APKiwi** [comment]
Thanks for the follow up. I'm unfamiliar with gradle: I'm using a clone of the repo and `gradlew test` results in:

```
BUILD SUCCESSFUL in 877ms
4 actionable tasks: 4 up-to-date
Watched directory hierarchies: [C:\Users\anton\DinkPlugin]
```

But even with `TEST_WEBHOOK_URL` set and verified in my terminal I don't get notifications. I'm sure I'm missing some steps

**Comment by APKiwi** [comment]
As I wrote that, I noticed your above comment with the required args `./gradlew test --tests dinkplugin.notifiers.PetNotifierTest.testNotifyClan`

This works as expected, thanks guys!

**Comment by APKiwi** [comment]
@iProdigy is there a way to view all available args?

**Comment by iProdigy** [comment]
You can consult the metadata classes to see what fields can be sent (if I am correctly understanding your question): https://github.com/pajlads/DinkPlugin/tree/master/src/main/java/dinkplugin/notifiers/data

**Comment by APKiwi** [comment]
Not sure where exactly I'm going wrong but the following do _not_ work for me:

- `./gradlew test --tests dinkplugin.notifiers.BossNotifierTest` (build fails)
- `./gradlew test --tests dinkplugin.notifiers.CombatAchievementNotifierTest` (build fails)
- `./gradlew test --tests dinkplugin.notifiers.GambleNotifierTest` (compiles, does nothing)


The following work as expected:

- `./gradlew test --tests dinkplugin.notifiers.ClueNotifierTest`
- `./gradlew test --tests dinkplugin.notifiers.CollectionNotifierTest`
- `./gradlew test --tests dinkplugin.notifiers.DeathNotifierTest`
- `./gradlew test --tests dinkplugin.notifiers.DiaryNotifierTest` (a bit odd, sends Karamja hard 3 times, then Desert elite, then Western Prov hard)
- `./gradlew test --tests dinkplugin.notifiers.LootNotifierTest`
- `./gradlew test --tests dinkplugin.notifiers.PetNotifierTest`
- `./gradlew test --tests dinkplugin.notifiers.PlayerKillNotifierTest`
- `./gradlew test --tests dinkplugin.notifiers.QuestNotifierTest`
- `./gradlew test --tests dinkplugin.notifiers.SlayerNotifierTest`
- `./gradlew test --tests dinkplugin.notifiers.SpeedrunNotifierTest`

**Comment by iProdigy** [comment]
`BossNotifierTest` & `CombatAchievementNotifierTest` aren't class names; replace them with `KillCountNotifierTest` and `CombatTaskNotifier`, respectively

I'm unable to reproduce your issue with `GambleNotifierTest`:
![image](https://user-images.githubusercontent.com/8106344/233822780-bf0bd8d1-b354-48e6-9952-a494cad52cd4.png)

**Comment by APKiwi** [comment]
Thank you, I can confirm that the KillCount and CombatTask classes are working.

GambleNotifier builds and runs successfully, but nothing is ever submitted to my API, each of the other classes has now successfully worked, however.

**Comment by iProdigy** [comment]
If you change the test url to a discord webhook instead of your API, does the gamble message appear?

If not, any luck if you do `./gradlew clean` first?

**Comment by APKiwi** [comment]
Both `./gradlew clean` and using a discord webhook instead, do not function for me :(

**Comment by iProdigy** [comment]
Okay I found an async bug with the test suite for screenshot handling, but it is strange that it's only manifesting for the gamble notifier (& not kill count). Regardless, you can workaround this by disabling `gambleSendImage` in `GambleNotifierTest`: change `true` to `false` on L43, L63, L78, and L102

**Comment by APKiwi** [comment]
Thank you, that works great.

I do note that I have only roughly 50% of my tests with images, some of them the same type, so this would indicate an async issue (that I ignored not knowing which should have images).

**Comment by iProdigy** [comment]
Instead of disabling `gambleSendImage`, could you test if changing L138 of DiscordMessageHandler from `thenAcceptAsync` to `thenAccept` also solves the issue?

As for the test images, *most* of the tests do not include any image & for the ones that do, it's a constant unrelated [image](https://github.com/pajlads/DinkPlugin/blob/master/src/test/resources/screenshot.png). (this part's not an async bug, just us being lazy)

**Comment by APKiwi** [comment]
Can confirm, changing `DiscordMessageHandler` L138 to `thenAccept` (after reverting `gambleSendImage`) correctly sends the image and tests correctly :)
