### ISSUE TITLE
Add collectionlog.net to Player Lookup Service

### ISSUE THREAD

**Issue by Newbcake** [pajlads/DinkPlugin#220]
Some players care more about the collection log than xp, therefore I'd like to request adding https://collectionlog.net/ profiles to the Player Lookup Service.

The URI for this is: https://collectionlog.net/log/<Username\>

This does require the player to have their profile tracked on that website, but so do the currently supported services; cml, temple and wom. So I don't see an issue here.

**Comment by pajlada** [comment]
Sounds good to me!

For anyone new looking to contribute, the relevant code is in the `PlayerLookupService.java` file.
Testing the new service enum can be done by running our unit tests (documentation available [here](https://github.com/pajlads/DinkPlugin/blob/master/docs/TESTING.md)) and modifying the `MockedNotifierTest.java` file to use a different PlayerLookupService value.
