### ISSUE TITLE
Improve plugin description

### ISSUE THREAD

**Issue by pajlada** [pajlads/DinkPlugin#228]
The description that shows in the client when you search for dink or webhook or notification is:

`A notifier for sending webhooks to Discord or other custom destinations`

Since the description can only fit very few words, I think we can come up with something better that more accurately describes what the plugin does.

**Comment by APKiwi** [comment]
`Universal discord webhook/API notifications with additional JSON`?

I think it's important to include key words like Discord, notifications, webhook and API, at least from a developer stand point webhook and API are what I would search for.

Hopefully this increases exposure as originally I didn't come across your plug-in until referred by iProdigy from another notifier plugin.

**Comment by notheowner** [comment]
> `Universal discord webhook/API notifications with additional JSON`?
> 
> I think it's important to include key words like Discord, notifications, webhook and API, at least from a developer stand point webhook and API are what I would search for.
> 
> Hopefully this increases exposure as originally I didn't come across your plug-in until referred by iProdigy from another notifier plugin.

I disagree partly with this, I feel like plugin hub tags could serve this purpose, as the majority of people using this plugin are not developers. People already don't look at plugin descriptions, if they see stuff like API and JSON in the description, they just don't know what you are on about.
The name already puts the plugin in a disadvantage way down the list, among the dozens of abandoned discord notifier plugins, the next visible part when you search something is the description, so it should be clear as day what the plugin does to the average user.
![RuneLite_CRQFpeDE8O](https://github.com/pajlads/DinkPlugin/assets/86596679/0d5727b6-b758-4148-b4c4-61668eb0bed4)

**Comment by iProdigy** [comment]
how about: `Discord-compatible webhooks for Loot, Death, Levels, CLog, KC, Pets, Diary, Quests, etc.`
