### ISSUE TITLE
Barbarian Assault Penance Queen Kill Screenshot

### ISSUE THREAD

**Issue by dansosrs** [pajlads/DinkPlugin#232]
I help run a bingo event where automating the posting of a screenshot whenever someone kills the penance queen would be great to automatically track. This could be either when the queen dies or when the player is sent back to the lobby. Additional things that would be nice but not needed would be the names of teammates and the role the user was.

**Comment by pajlada** [comment]
I've marked this as "New notifier", but I imagine we could rename our "BA Gambles" category to "Barbarian Assault" and have this notifier in there too if we'd want to.

There's a dialog that shows up when the user enters the lobby, I think that would be an easy event to catch & fire on.

**Comment by dansosrs** [comment]
the comp that it would be great to use this for starts in mid september, if anyone has some time I would greatly appreciate it before then. thanks
