### ISSUE TITLE
Loot icon embedded instead of seperate

### ISSUE THREAD

**Issue by emiljensen2** [pajlads/DinkPlugin#233]
Any possibility of the loot icon being embedded in the rich embed instead of the rare drop table image at the top right. It would look way better.

How it looks right now: 
![image](https://github.com/pajlads/DinkPlugin/assets/25011746/256ca261-d860-448c-9b33-ef2c7a90ffa8)

How another plugin handles it: ![image](https://github.com/pajlads/DinkPlugin/assets/25011746/c74b853a-0659-4e51-876d-ed39ba829fee)

**Comment by TomBolks** [comment]
Should be possible, only when a loot drop contains multiple items one item needs to be chosen for the icon.
I think it should be the highest value item stack or the most rare if https://github.com/pajlads/DinkPlugin/pull/141 ever progresses

**Comment by Felanbird** [comment]
@emiljensen2 We went ahead and applied your suggestion as the icon that's always used, to prevent removal of previous functionality from the embed setting.

When the next version comes out you'll see the most expensive item as the icon, and if you no longer want the additional embeds you can disable the embed setting. 
![image](https://github.com/pajlads/DinkPlugin/assets/41973452/b68797a3-6be8-4a59-908f-36678d4b978e)
