### ISSUE TITLE
200M experience notification

### ISSUE THREAD

**Issue by pajlada** [pajlads/DinkPlugin#244]
Currently, our post-99 notifications are enabled with the "Notify on Virtual Levels" option - I feel like this option should also notify when the user reaches 200M experience

There are some things that would need to be tested in-game for this feature to make sure it doesn't continue to notify

1. When a user has 199,999,999 XP and receives 2 XP
2. When a user has 200,000,000 XP - what do further skill change events look like?

**Comment by Felanbird** [comment]
> When a user has 200,000,000 XP - what do further skill change events look like?

Adam suggests a fake xp drop comes in at a different time than normal post 200m, but NFC also mentions that said fake xp drop can happen for ironmen in PvP situations, not requiring 200m xp.
