### ISSUE TITLE
Feature: Add config to hide GIM group name

### ISSUE THREAD

**Issue by TomBolks** [pajlads/DinkPlugin#245]
I would like to remove the GIM group name from the storage notification. How I and my group use it is that we don't have a multiple groups posting to the same discord channel, we always know its our group. So its only clutter.

Config to remove the group name? Haven't digged alot through the code but a simple config checkbox at https://github.com/pajlads/DinkPlugin/blob/master/src/main/java/dinkplugin/notifiers/GroupStorageNotifier.java#L205 should work?

**Comment by pajlada** [comment]
Seems reasonable to me - the "Group" field should be omitted if this config is used.

Preferably the data would still exist in the `extra` field, so might be a bit more complicated than just setting `groupName` to an empty string

**Comment by iProdigy** [comment]
Though would be much easier to omit from `extra`, which would also avoid someone with a privacy use case being confused why the name still sent to a custom url

**Comment by pajlada** [comment]
That's true, I guess the use-case for omitting the group name from discord but including it in the extra field for a custom receiver would be pretty rare, and can be handled once that comes up

**Comment by iProdigy** [comment]
@TomBolks did you want to be assigned this PR or should I get it?

**Comment by TomBolks** [comment]
@iProdigy Thanks for asking, but I don't really have the time for it. Otherwise I would probably made the PR already :p
