### ISSUE TITLE
Improve Death loot value for noted/stackable items

### ISSUE THREAD

**Issue by JamsRepos** [pajlads/DinkPlugin#252]
Loot value for inside looting bag and noted items does not count to the worth. Is there a way to incorporate this?

**Comment by Felanbird** [comment]
I'm confused what the point of this request is. 

The point of the loot notifier is to fire notifications based on loot you receive, not loot you pile up and then randomly look at. 
I can't even imagine how awful it would be when literally everytime you open the looting bag, it thinks you looted that much loot, and sends a notification.


Also to be sure, I went ahead and checked and noted loot definitely counts on the loot notifier.
![image](https://github.com/pajlads/DinkPlugin/assets/41973452/a9fa474d-4434-4f0d-bfb7-c95dde59a92a)

**Comment by JamsRepos** [comment]
This was worded wrong, it’s the loot value for a death.

**Comment by Felanbird** [comment]
> This was worded wrong, it’s the loot value for a death.

The word death seems very important for your point.

**Comment by JamsRepos** [comment]
> > This was worded wrong, it’s the loot value for a death.
> 
> The word death seems very important for your point.

You don’t say, forgot people aren’t allowed to make mistakes.

**Comment by Felanbird** [comment]
You are allowed to make mistakes, what you're not allowed to do is immediately get defensive and act offended when I point out your mistake was forgetting the absolute most important word for getting your point across.

**Comment by JamsRepos** [comment]
> You are allowed to make mistakes, what you're not allowed to do is immediately get defensive and act offended when I point out your mistake was forgetting the absolute most important word for getting your point across.

Not quite sure you’re in a place to tell me what I’m allowed and not allowed to do but sure, if you think I took offence then you’re wrong, your response was not needed at all, you just had to come across with the passive aggressiveness so I responded accordingly. 

I corrected myself and you took it upon yourself to state the obvious when I had already corrected myself the message just before.

**Comment by iProdigy** [comment]
Noted items *should* already count to the value calcuation in the death notifier; the approach used in the loot notifier to look up the value of noted items is exactly the same for the death notifier

Looting bags, on the other hand, are hard to reliably track (and other plugins that already exist to just achieve this one task have unsolved edge cases)

**Comment by JamsRepos** [comment]
> Noted items _should_ already count to the value calcuation in the death notifier; the approach used in the loot notifier to look up the value of noted items is exactly the same for the death notifier
> 
> Looting bags, on the other hand, are hard to reliably track (and other plugins that already exist to just achieve this one task have unsolved edge cases)

Yeah, thought so. I had died with a bunch of noted superiors earlier at the chaos altar and only the un-noted counted towards my death. Said I died for 110k worth when it was more like a million.

A bunch of people in my Discord also do wilderness bossing and they too don’t get accurate deaths so it was just asking if this was intentional or not and it seems like it’s a technical limitation.

**Comment by iProdigy** [comment]
I think you're running into another technical limitation: the plugin has to make a best guess at which items are kept and which are lost (it likely thought the noted stack was kept rather than lost)

**Comment by JamsRepos** [comment]
> I think you're running into another technical limitation: the plugin has to make a best guess at which items are kept and which are lost (it likely thought the noted stack was kept rather than lost)

Ah so, rather than thinking it was a stack of items it assumed it was just one item?

**Comment by iProdigy** [comment]
> Ah so, rather than thinking it was a stack of items it assumed it was just one item?

No, it correctly sees the item count. What else was in your inventory/armor? (one explanation is the plugin thought your noted superiors were *kept* and some piece of armor was lost, when reality was the other way around)

**Comment by JamsRepos** [comment]
> > Ah so, rather than thinking it was a stack of items it assumed it was just one item?
> 
> No, it correctly sees the item count. What else was in your inventory/armor? (one explanation is the plugin thought your noted superiors were _kept_ and some piece of armor was lost, when reality was the other way around)

I had a Burning Amulet on as well as a Ring of Wealth. I kept the Ring of Wealth and 2 notes bones.

**Comment by iProdigy** [comment]
In your RuneLite settings, do you have wiki prices disabled?

![image](https://github.com/pajlads/DinkPlugin/assets/8106344/02909a81-dccb-4e8a-a689-336a61223266)

&nbsp;

Also I don't quite follow; were you skulled with protect prayer on to only keep two item stacks? & 2 noted bones was kept over ~100 superiors (as you said 1M gp)?

**Comment by JamsRepos** [comment]
> In your RuneLite settings, do you have wiki prices disabled?
> 
> ![image](https://user-images.githubusercontent.com/8106344/242448597-02909a81-dccb-4e8a-a689-336a61223266.png)
> 
>  
> 
> Also I don't quite follow your item accounting; what was the full inv & item stacks that were kept?

I believe I’ve got whatever is default, I won’t be able to check as I’m moving house today. 

I’m not sure what you mean. I had a burning amulet and ring of wealth equipped and I had the cash to exchange the bones as well as 300 noted superiors and around 10 un-noted when I died. So I kept, the ring of wealth and two noted bones when I died.

**Comment by pajlada** [comment]
We don't have very good tests when it comes to noted items, we can look into it to see if we can make the death notifier better at guessing what you lost

**Comment by iProdigy** [comment]
Investigated this and found the issue: stacks of noted items are not "unstacked" for the kept/lost item logic, so the notifier thinks you can keep the full stack of noted bones when you can only keep a few of the individual noted items and the rest of the stack is lost. Working on a fix now
