### ISSUE TITLE
Boss Speed-Running

### ISSUE THREAD

**Issue by Shawneh** [pajlads/DinkPlugin#259]
Has there been any thought into having personal best times from bosses as a webhook?

**Comment by pajlada** [comment]
This is already possible with the `Kill Count` notifier, make sure to have the `Personal Best` setting enabled, that way it will send a notification any time you beat your personal best.

![image](https://github.com/pajlads/DinkPlugin/assets/962989/1ddec9e1-bc72-4161-aca7-375e9d1bc3be)

There's currently no way to disable the interval notifications, so you'd have to set it to some high number you'll never reach to never get an interval notification.
