### ISSUE TITLE
Migrate from `Skill.OVERALL` to `something else`

### ISSUE THREAD

**Issue by Felanbird** [pajlads/DinkPlugin#261]
https://github.com/runelite/runelite/commit/d9c5fe55f2fcfe8875235606caed96c26e468ec3

I couldn't easily figure out what we do now

**Comment by iProdigy** [comment]
Upon the next RL release, we can remove https://github.com/pajlads/DinkPlugin/blob/191db5fac82c00e09b5091a40d578ad14ac09ec4/src/main/java/dinkplugin/notifiers/LevelNotifier.java#L63

**Comment by Felanbird** [comment]
runelite/runelite@a1fe5f80c046d025bc8026936abf0957ecf9c3e4
