### ISSUE TITLE
Include extra.groupName on all events

### ISSUE THREAD

**Issue by APKiwi** [pajlads/DinkPlugin#271]
As group ironmen it would be useful to include `extra.groupName` on all events, firstly to be able to format embeds/messages to include the group name (our discord has 3 group irons in it) and secondly for the reason I address below (caching the value as early as possible). Hopefully that doesn't add much overhead to the events?

As an aside, the `GROUP_STORAGE` event does not always emit the `extra.groupName`, sometimes it comes through as `undefined`. I have been able to recreate it only rarely when first booting the game, and immediately using the storage, typically for withdraw events. I tried a number of methods, but I'm unable to re-create. I also only have internal API POST logs, which simply say `undefined`, I have no client logs.

I've catered my DB to cache and store users + groups in tables to use the cached value instead of the `groupName` variable; but thought you should know in case you can spot an easy fix.

**Comment by iProdigy** [comment]
For the missing group names, if it's not an immediate transaction upon login (before jagex has sent the client the group name), you might have users that disabled the `Include Group Name` config option.

**Comment by APKiwi** [comment]
Most likely the former, as suspected something to do with the initial load of the client. They both confirm it is ticked when I asked to review their config, and was only happening 2/10 times.

**Comment by iProdigy** [comment]
Thanks for checking on that - on our end it's nontrivial to delay storage notifications until the group name is available (especially if we decide to include this field across all notifiers) so I would continue to use your cache workaround. Users could also click on the Grouping interface to display the group name (which would ensure the server has sent the client the group name) before making shared storage transactions (but this can be tedious for users)

Nonetheless, I'll talk to the other maintainers about your feature request
