### ISSUE TITLE
Grand Exchange Bought/Sold Notifications

### ISSUE THREAD

**Issue by pascalla** [pajlads/DinkPlugin#272]
Would be nice if you could have a bought/sold webhook for grand exchange transactions.

**Comment by iProdigy** [comment]
Would it be sufficient to only send a notification if the buy/sell offer is fully completed (i.e., ignore partially complete offer updates)?

If so, do we completely ignore cancelled offers that had partial progress?

**Comment by pascalla** [comment]
> Would it be sufficient to only send a notification if the buy/sell offer is fully completed (i.e., ignore partially complete offer updates)?
> 
> If so, do we completely ignore cancelled offers that had partial progress?

My specific use case I had in mind would only really care about fully bought/sold. But I think maybe having the best of both worlds and having a setting to enable partial completions.

**Comment by Felanbird** [comment]
Prodigy and I discussed this last night and my main concern is _how_ do we do partial completions.

Are we really sending a notification every time somebody buys 5 or 10 of my 100 dragon implings? Does that not get annoying?

I do have my own extreme example of selling cooked sweetcorn for 1499gp over about 2 years, but in that case the notifications happen so sparsely that it was kind of interesting.

**Comment by APKiwi** [comment]
You could consider storing a guid for each transaction and sending out events with that guid (at least for custom backends). But that might be worth a few story points.

**Comment by iProdigy** [comment]
Unfortunately we don't receive enough information from runelite to reliably create guid's without some edge cases of conflicts
