### ISSUE TITLE
Whisperer Do not give any updates when killing i think this one is bugged

### ISSUE THREAD

**Issue by Ardit4liu** [pajlads/DinkPlugin#282]

**Comment by Felanbird** [comment]
As far as I'm aware Whisperer notifs work (almost) exactly as expected, the almost being there's no loot in the Kill Count notifs due to her delay before loot spawns.

**Comment by iProdigy** [comment]
Related https://github.com/pajlads/DinkPlugin/issues/281#issuecomment-1655844051 & https://github.com/runelite/runelite/commit/c2dfda9ede854a5d3f8aeabd1facee36d3951568

**Comment by iProdigy** [comment]
This is caused by Runelite deciding to only fire `LootReceived` for whisperer loot instead of the normal `NpcLootReceived`, unlike their approach for all of the other DT2 bosses. We will implement a workaround for this decision in Dink v1.6.1
