### ISSUE TITLE
Loot: Send loot with screenshots to another webhook

### ISSUE THREAD

**Issue by CypherNL** [pajlads/DinkPlugin#283]
I am in a Discord channel that has an "all-drops" and "rare-drops" text channels. Using Dink for the all the drops and Discord Rare Drop Notifier for the rare drops channel.

Recently, i have noticed the Rare Notifier plugin doesn't post rare drops from the new DT2 bosses which I'm considering to drop that plugin. I would've liked to use Dink for the rare-drops text channel to make every notification consistent with the styling but there's not an option to do both all drops and rare drops unless there's a way to get two Dink instances running in RuneLite.

Then occurred me that there is an option to post screenshots above a certain value which could be a good identifier for a rare drop. But there isn't a way to post loot with screenshots to a different text channel.

My ideal situation is that Dink posts every drop including screenshots in the all-drops text channel and the drops with a screenshot in the rare-drops channel.

Could this be realized? An option to do this in Dink would be ideal. But I'm not aware if there's a way to do this in Discord with item icons enabled since that also counts as posts with images.

**Comment by pajlada** [comment]
This is a bit of a tricky one, you'd basically want two separate Loot notifiers active with different settings & different webhooks.
It can 100% be achieved outside of Dink using a middleware web server that looks at the notification and then pushes it to the correct webhook as necessary, but that might not be a feasible solution for you.

**Comment by iProdigy** [comment]
As pajlada suggested, you can achieve this (for free*) by pointing the webhook to a cloudflare worker (or aws lambda) that inspects `extra` & forwards the message to the appropriate discord webhook

Some resources to help:
* https://developers.cloudflare.com/workers/examples/read-post/
* https://developers.cloudflare.com/workers/examples/post-json/
