### ISSUE TITLE
Whisperer Awakener's Orb Not Notifying

### ISSUE THREAD

**Issue by jdanthdavis** [pajlads/DinkPlugin#291]
Received an Awakener's Orb and did not receive a Discord notification. We also did not receive a notification for Loot (did for Collection Log) when a vestige from The Whisperer was dropped. However, we do get all Collection Log notifications whether they're untradeable or not from The Whisperer.

![image](https://github.com/pajlads/DinkPlugin/assets/87504521/d0a1247a-1146-463c-ba39-5424d41e1eea)

**Comment by Felanbird** [comment]
Loot tracker doesn't work for Whisperer again, Jagex broke Runelite's implementation.

It won't work until the next Runelite version

**Comment by jdanthdavis** [comment]
> Loot tracker doesn't work for Whisperer again, Jagex broke Runelite's implementation.
> 
> It won't work until the next Runelite version

Thanks for the fast reply!

**Comment by iProdigy** [comment]
Whisperer loot notifications also requires https://github.com/runelite/plugin-hub/pull/4761 to be merged
