### ISSUE TITLE
Allow different notification message for dupe pets

### ISSUE THREAD

**Issue by asherbasher** [pajlads/DinkPlugin#292]
I believe it should be easy enough to differentiate given the game message is different when receiving a duplicate pet?

**Comment by Felanbird** [comment]
This isn't my favorite idea personally, but since there's literally nothing in the pet section, it seems fine.

**Comment by pajlada** [comment]
What type of customization is it that you're looking for here @asherbasher - the ability to change the Notification Message for duplicate pets, like in the Death notifier where we allow separate messages for PVP deaths? Or just the ability to disable duplicate pet notifications entirely?

**Comment by iProdigy** [comment]
At a minimum, we can include a boolean flag within the `extra` metadata to indicate dupe status (assuming collection log game setting is enabled)

Need more information on the use case to implement a change in the config / discord message behavior

**Comment by asherbasher** [comment]
@pajlada Yes, similar to the way it's handled in the death notifier.
My message for pets is:
`**%USERNAME%** has a funny feeling like he's being followed!`

Yesterday when I received a duplicate pet it outputted this message and people assumed it was a new pet. Would be nice to be able to change the message to _would have been followed_ so people are able to see it's a duplicate.

**Comment by iProdigy** [comment]
![image](https://github.com/pajlads/DinkPlugin/assets/8106344/3d0cb279-a298-4b2b-82f3-fd85708aed58)
