### ISSUE TITLE
Please add discord thread support for webhooks.

### ISSUE THREAD

**Issue by Osamu01** [pajlads/DinkPlugin#294]
title says it all. would be even better if it could support tags, because then we could post all our webhooks to one channel and have it auto tag itself as 'loot' or what have you, to easily be sorted through.

**Comment by Felanbird** [comment]
Discord webhooks already support threads, just put `?thread_id=IDHERE` at the end of the webhook
![image](https://github.com/pajlads/DinkPlugin/assets/41973452/94b54faf-4e8f-4ded-9fdd-9a70eb890781)

**Comment by Osamu01** [comment]
> Discord webhooks already support threads, just put `?thread_id=IDHERE` at the end of the webhook ![image](https://user-images.githubusercontent.com/41973452/261914089-94b54faf-4e8f-4ded-9fdd-9a70eb890781.png)

Is it possible to have it create a new thread as opposed to comment in one?

**Comment by Osamu01** [comment]
> > Is it possible to have it create a new thread as opposed to comment in one? also can tags be added?
> 
> ~It's not a discord bot so no, it only interacts with what webhooks can interact with.~ The same answer for adding tags. edit: It seems we could [create threads](https://discord.com/developers/docs/resources/webhook#execute-webhook), but still not tag them.

Thank you for all of your help, this is awesome. I am having an issue with using `?thread_name=loot` though, as it's not creating a thread. Do you have any idea what my issue might be?

**Comment by Felanbird** [comment]
> Thank you for all of your help, this is awesome. I am having an issue with using `?thread_name=loot` though, as it's not creating a thread. Do you have any idea what my issue might be?

For thread_name it's something we would have to add internally, it's not done by adding it to the webhook like thread_id was

**Comment by Osamu01** [comment]
> > Thank you for all of your help, this is awesome. I am having an issue with using `?thread_name=loot` though, as it's not creating a thread. Do you have any idea what my issue might be?
> 
> For thread_name it's something we would have to add internally, it's not done by adding it to the webhook like thread_id was

I see. Is this an update I could look forward to?

**Comment by iProdigy** [comment]
Note: `thread_name` is only supported for "forum" discord channels - webhooks cannot create threads in normal text channels

If your use case is for forum channels, yes I can look into adding support

**Comment by Osamu01** [comment]
> Note: `thread_name` is only supported for "forum" discord channels - webhooks cannot create threads in normal text channels
> 
> If your use case is for forum channels, yes I can look into adding support

yes I would love that. right now I have created threads for it to post under, but I originally wanted to create threads per post. This would be more ideal given discords behavior of hiding inactive posts, afaik indefinitely.

**Comment by iProdigy** [comment]
> I originally wanted to create forum threads per post

Could you clarify _why_ you want a new thread per notification? You alluded to a sorting benefit, but I'm not quite following (given that automatic tagging is not possible from our end)

&nbsp;

> more ideal given discords behavior of hiding inactive posts

You could set the inactivity period to 7 days, so threads only hide if no notification has occurred in a week. If a thread does get hidden for inactivity, a new notification should unhide the thread for everyone subscribed.

**Comment by Osamu01** [comment]
> > I originally wanted to create forum threads per post
> 
> Could you clarify _why_ you want a new thread per notification? You alluded to a sorting benefit, but I'm not quite following (given that automatic tagging is not possible from our end)
> 
>  
> 
> > more ideal given discords behavior of hiding inactive posts
> 
> You could set the inactivity period to 7 days, so threads only hide if no notification has occurred in a week. If a thread does get hidden for inactivity, a new notification should unhide the thread for everyone subscribed.

If I'm able to set a custom title per post then it's nice considering I personally could make my own bot to assign tags. I don't really mind how I have it right now so it's not as if it needs to be changed, but it just seems more intuitive.

**Comment by iProdigy** [comment]
and so I'm on the same page - what's the benefit of that approach over creating a separate thread per notif type (and specifying each thread as a webhook override)?

**Comment by iProdigy** [comment]
For the custom title per notification type, do you need a separate box per notifier or would a single box with template replacements work? For example: ``%TYPE%`` could be loot, death, etc. so you could have a template like: `%TYPE% for %USERNAME% at %TIMESTAMP%`

**Comment by Osamu01** [comment]
> For the custom title per notification type, do you need a separate box per notifier or would a single box with template replacements work? For example: `%TYPE%` could be loot, death, etc. so you could have a template like: `%TYPE% for %USERNAME% at %TIMESTAMP%`

the %type% thing works, and again the benefit is mostly being able to view it a different way.

**Comment by iProdigy** [comment]
Forum tags via webhook was documented in https://github.com/discord/discord-api-docs/pull/6560, so we are implementing that part of your request now!
