### ISSUE TITLE
Add total level count variable via %TOTAL_SKILLS%

### ISSUE THREAD

**Issue by Weiqiiing** [pajlads/DinkPlugin#295]
An additional value that could be added to grab the total level of the player would be nice!

Example:
`%USERNAME%` has levelled `%SKILL%` - Total Level: `%TOTAL_SKILLS%`
`Weiqiiing` has levelled `Thieving to 99` - Total Level: `2121`

**Comment by Felanbird** [comment]
I believe currently we don't ever think about total level, we just send all levels separately (for JSON purposes), but I can't think of any reason we can't use that information to generate `%TOTAL_SKILLS%`
