### ISSUE TITLE
Is it possible to also include the KC of when a drop happens?

### ISSUE THREAD

**Issue by UmaLPZ** [pajlads/DinkPlugin#296]
The plugin works great but I was hoping there would be a way to also include the KC for the drop as well. I'm not too familiar with how the code works, but it should be at least possible to include the bosses' KC. Non boss npc kills, pickpockets, and chest openings, etc. might be a little more complicated.

Again, I'm not very knowledgeable about how the code works, but if this seems possible based on what is available from other plugins then I'm more than happy to help it whatever way I can.

**Comment by iProdigy** [comment]
Yes, this is possible for NPCs by reading data from the base loot tracker plugin - I won't attempt to support other loot sources initially as there's too many possibilities
