### ISSUE TITLE
WANT: Option to disable GE Prices

### ISSUE THREAD

**Issue by ItalecCallus** [pajlads/DinkPlugin#297]
Hey! I love what you did with this plugin being an all in one and my only issue Id have to raise is that I am an ironman and don't really care about GE Prices being shown especially when depositing/withdrawing from group storage. So, If you could potentially add an option to disable these that would be fantastic! I also attached an image on exactly what I am talking about!
P.S. Id create a pull request for you but I do not have software to do this :(
![Screenshot_1](https://github.com/pajlads/DinkPlugin/assets/143108932/c212b4d2-992b-45c1-ae20-84587abffc8e)

**Comment by iProdigy** [comment]
You can disable GE prices across the plugin (and other plugins) by turning off wiki prices in RuneLite settings:

![image](https://user-images.githubusercontent.com/8106344/242448597-02909a81-dccb-4e8a-a689-336a61223266.png)

**Comment by pajlada** [comment]
@iProdigy They're looking to disable the price entirely, making it only say
```diff
... has deposited:
+ 12 x Ranarr seed
+ 1 x Saradomin sword
+ 15 x Grimy ranarr weed

... has withdrawn:
N/A
```

**Comment by iProdigy** [comment]
Ah, yes we could add a config option for gim bank notifier to exclude prices altogether (rather than switch GE to store prices)

**Comment by ItalecCallus** [comment]
Thank you both so much <3 and thanks for the helpful tip too about the runelite settings!

**Comment by pajlada** [comment]
@ItalecCallus This will be available in the next release

You will have to disable the option called "Include Price"
![image](https://github.com/pajlads/DinkPlugin/assets/962989/66400373-26ca-4cf0-ac8e-1e7c3e85da9a)

It will look like this:
![image](https://github.com/pajlads/DinkPlugin/assets/962989/2ca2dadc-480e-47c9-9cd2-eef299c9b328)

There's currently no ETA for the next release
