### ISSUE TITLE
Reopen discussion on rsn whitelist option

### ISSUE THREAD

**Issue by Newbcake** [pajlads/DinkPlugin#305]
I would once again like to request a rsn whitelist feature.

I am the original requester of this feature (https://github.com/pajlads/DinkPlugin/issues/111), and even though a whitelist suited my use case at the time. Over the last year multiple friends have expressed disappointment of not being able to configure a whitelist. For some friends this was a deal breaker and they chose to stick to other (older/abanonded) plugins even they prefer the features of Dink. Therefore I now believe the user should be able to choose between a whitelist and an ignorelist.

I understand it could be confusing for some users and therefore propose the following:

A menu called 'Filter mode' that allows the user to choose between 'Allow all RSNs' and 'Ignore all RSNs', this option would sit above the current input box for RSNs. This way of doing is is not unheard of in runelite plugins, for example the [Clan Spam Filter](https://github.com/andreasx23/GuildSpamFilter) plugin has a similar toggle:

![JLGyomp](https://github.com/pajlads/DinkPlugin/assets/9064744/06636921-70c2-47da-a081-027eda777544)

The current 'Ignored RSN's' input box would also be renamed to a more apt 'RSN list' or 'List of RSNs' input box, as well as the tooltip.
In addition the default should still be set to 'Ignore all RSNs' so that the plugin doesn't break if a user fails to spot the configuration option.

Happy to go back on forth on this if needed, it really is a feature me and my friend group would love to see.

Thanks!

**Comment by Felanbird** [comment]
https://github.com/pajlads/DinkPlugin/issues/177#issuecomment-1441805094

**Comment by Newbcake** [comment]
Yes I've read that issue, a friend of mine made that. And I touched on your concerns in my issue here.

**Comment by pajlada** [comment]
I would be open to having it be a denylist, as long as it requires extra steps to enable.
I would be ok with doing some exploration to see if it's viable for us
