### ISSUE TITLE
Feature request: Make generic achievement metadata more accesible

### ISSUE THREAD

**Issue by J3sven** [pajlads/DinkPlugin#320]
I am currently working on making an OSRS 2011-style adventurer's log (see pic). It is using Dink as it's engine for pushing log data (admittedly not the intended usecase). I chose Dink because it is avaiable in both HDOS as well as Runelite.

![firefox_F7NBRXQF7b](https://github.com/MidgetJake/UniversalDiscordNotifier/assets/18210607/7a8182a2-007d-4f57-9967-7835b9b12249)

repo: https://github.com/J3sven/OSRS-alog

One issue I am facing with Dink right now is that the (combat) achievement, Quest point and Collectionlog counters do no update until a relevant event has occured. A method of accessing this data more readily would be much appreciated, especially considering accounts with any of these stats maxed would never see an update until their cap is raised.

Some suggestions:

- Simply include the data in every webhook request (perhaps a bit overkill)
-  A generic log in/log out notification that lists the user's stats and achievement data. This could be something desirable for general users too as a reference of what progress they made that day.

**Comment by Mm2PL** [comment]
I don't think the first idea is the way to go, having optional data like that in all payloads sent out greatly increases their complexity. Currently we don't hide much metadata like that and I don't think we should. Just filter events sent to the webhook.
Having a more generic data sync on log-in/log-out might be more beneficial including for other uses.

Also worth noting that we are not in control of HDOS' fork of our plugin. It's closed source and integrated into the client itself.

**Comment by svenvdl** [comment]
I am aware about the HDOS side of things, but me and brainfree speak fairly regularly so I think that won't cause much delay :)

**Comment by J3sven** [comment]
I am aware that the HDOS fork is separate from the main repo, me and brainfree do speak fairly often and he is aware of the project so if a patch were to land I could probably give him a nudge to get it integrated :)

**Comment by J3sven** [comment]
> Having a more generic data sync on log-in/log-out might be more beneficial including for other uses.
After some sleep I would like to mention that if you guys do decide to go down this road you will probably want to keep track and maybe only fire the event once per daily reset or 24h local time, as to not spam the user if they go worldhopping a bunch.

**Comment by Felanbird** [comment]
Our thought-process was to fire it only to non-discord integrations, it would basically have no impact on the user & the handler could just ignore them where applicable.

**Comment by J3sven** [comment]
> Our thought-process was to fire it only to non-discord integrations, it would basically have no impact on the user & the handler could just ignore them where applicable.

Oh that makes a lot of sense, for sure!
