### ISSUE TITLE
feat: Add color picker for rich embed

### ISSUE THREAD

**Issue by tylersfd2** [pajlads/DinkPlugin#322]
rich embed color options

**Comment by pajlada** [comment]
Could you elaborate on this request?
Right now this uses our brand colors as defined in [Utils.java](https://github.com/pajlads/DinkPlugin/blob/master/src/main/java/dinkplugin/util/Utils.java#L47-L49) and I hesitate to make it configurable just on a whim

**Comment by tylersfd2** [comment]
If it's not too much work, it would be nice to have the dink rich embeds match the branding of the other embeds in the channels. Thanks for the quick response
