### ISSUE TITLE
Loot broadcasts showing kc from loot tracker, not actual kc

### ISSUE THREAD

**Issue by zlost7** [pajlads/DinkPlugin#323]
Currently loot broadcasts are displaying the kc previously recorded by the loot tracker, not the actual account kc. 
Image below for reference (account has 2700+ kc but broadcast says 211)
Thanks
![image](https://github.com/pajlads/DinkPlugin/assets/146493262/ea8d9fbf-5df3-44cc-8c74-867104aafc32)

**Comment by Felanbird** [comment]
It's intended to only use loot tracker count, we didn't make it use boss KC yet.

**Comment by zlost7** [comment]
Are there any plans on adding boss KC? Thanks

**Comment by Felanbird** [comment]
> Are there any plans on adding boss KC? Thanks

yes

**Comment by zlost7** [comment]
sweet, thanks for the quick replies

**Comment by iProdigy** [comment]
Keeping this open until we incorporate chat KC in loot notifications
