### ISSUE TITLE
[Bug] CG deaths are considered dangerous for non-hardcore accounts

### ISSUE THREAD

**Issue by jameshoffmann** [pajlads/DinkPlugin#326]
To test, die in CG to hunllef immediately after entering with "ignore safe deaths" toggled OFF, and set min lost value to 4. The death will not track. 

Set min lost value to 3. Immediately die to hunllef, and it will track.

(These numbers are based off current GE pestle + mortar price, which is 3 gp as of 10/3/2023)

**Comment by Felanbird** [comment]
I'm confused with this report, you're reporting that when safe deaths are toggled OFF and your death does not meet the min value you've set, notifications don't fire, which is correct. When you do meet the min value, it does fire, which is also correct?

**Comment by jameshoffmann** [comment]
When you hover over the "Min lost value" setting, it says that this setting does not apply for safe deaths. 

I'm not sure if the behavior in the original post is intended or not, but to me it would make more sense to have safe deaths be tracked completely unrelated to min lost value.

**Comment by iProdigy** [comment]
Our logic was considering CG deaths as dangerous. We will change the logic to consider these deaths safe unless the account is hcim

**Comment by jameshoffmann** [comment]
Awesome, thanks

**Comment by jameshoffmann** [comment]
Could the same logic be applied to TOA? I just tested and I think it is bugged there as well @iProdigy

**Comment by Felanbird** [comment]
> Could the same logic be applied to TOA? I just tested and I think it is bugged there as well @iProdigy

We already did this in #317 - there just hasn't been a version bump
