### ISSUE TITLE
Feature request: Send account hash (or a derivative of it) along with display name

### ISSUE THREAD

**Issue by J3sven** [pajlads/DinkPlugin#333]
I was recently made aware of https://static.runelite.net/api/runelite-api/com/jagex/oldscape/pub/OAuthApi.html#getAccountHash()

For my application it would be a great help if events were to send along this hash or an unique identifier derived from it (e.g. sha256) to keep track of name changes.

**Comment by iProdigy** [comment]
While sending the raw long is easiest, I'm concerned some other plugins may be suboptimally designed and use the account hash as a sort of auth so perhaps we shouldn't provide the raw long to more third parties. 

Applying SHA384 is simple (guava has a convenient helper), and would prevent third party webhook handlers from knowing the raw long. Also this algo is resistant to length extension attacks (which would apply to md5, sha1, sha256, sha512) in case the backends for other plugins are doing `hash(secret || rawLong)`. Technically, HmacSHA256 is another option with these security guarantees but SHA-384 is 3x faster on my machine (according to jmh). 

Alternatively, if we don't care about badly designed backends for other plugins, we could just send the raw long
