### ISSUE TITLE
Incompatibility with Prestige

### ISSUE THREAD

**Issue by Mm2PL** [pajlads/DinkPlugin#336]
The [prestige plugin](https://runelite.net/plugin-hub/show/prestige) seems to cause issues with repeated dinks for the same real level. Dink always reports the real level unlike what prestige makes the game show.

![image](https://github.com/pajlads/DinkPlugin/assets/25011746/aa8e4545-8d03-4fb8-87b7-d3dd31b12f66)

**Comment by Felanbird** [comment]
Seems like the dupe level thing is a bug on their end https://togithub.com/ckosidow/prestige-levelling/issues/5

Outside of that bug, if you're downloading a plugin that says `A plugin that resets your level and doubles your xp rate`, this outcome is expected.

**Comment by iProdigy** [comment]
Closing this as flawed on Prestige's end
