### ISSUE TITLE
Speedrun notification doesn't work with Gauntlet/CG

### ISSUE THREAD

**Issue by edlloyd8** [pajlads/DinkPlugin#340]
:(

**Comment by iProdigy** [comment]
Thanks for the report! Indeed, `Challenge duration: 2:39 (new personal best).` would not match our current regex: https://github.com/pajlads/DinkPlugin/blob/master/src/main/java/dinkplugin/notifiers/KillCountNotifier.java#L48

This is easily fixed (will get to it later today)

**Comment by iProdigy** [comment]
Nevermind, `TIME_REGEX` is `CASE_INSENSITIVE`, so it should've matched...

Can you share a screenshot of your notifier settings?
