### ISSUE TITLE
Feature Request: Notification for Logout Timers

### ISSUE THREAD

**Issue by lheigl** [pajlads/DinkPlugin#349]
### Checklist

- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking suggestions.
- [X] I've checked the `Unreleased` section of the [changelog](https://github.com/pajlads/DinkPlugin/blob/master/CHANGELOG.md) for newly added features that sound like my suggestion.

### Describe your Suggestion

Add notification timers for logout alerts (4h,6h, etc)

### Reasoning

It'd be a ton of fun in friend groups to see what people are doing when they get nerd logged!

**Comment by iProdigy** [comment]
I'm tempted to add a chat notifier where folks can input any message patterns (e.g., the 6 hour logout message), and if an incoming game message matches a user-specified pattern, a webhook notification is fired

We can pre-populate the pattern config with this login message, and folks can specify other exotic game messages they care about, without needing separate notifiers
