### ISSUE TITLE
Deaths during `TzHaar-Ket-Rak` Challenges are always sent

### ISSUE THREAD

**Issue by Felanbird** [pajlads/DinkPlugin#365]
When we originally implemented the death notifier, Fight Cave and Inferno deaths were made exceptions to the `ignore safe deaths` setting because while they were safe deaths, your deaths during them would likely want to be seen, since a death was -1hr to not get your cape.

The problem with this is TzHaar-Ket-Rak's Challenges. These are challenges that happen in the Inferno room which once all of them are completed, give you a transmog for the Jad pet.

Due to the nature of these challenges, dying is _very_ common which means a lot of death notification spam, basically for something not many people would care about.
<br>

This issue exists just as a record of the problem, which I thought somebody would report, but nobody ever did.

**Comment by pajlada** [comment]
Did we confirm this is fixed by #363?

**Comment by Felanbird** [comment]
Yes I didn't actually test inferno, I tested this
