### ISSUE TITLE
No Loot Notification For PNM Drop

### ISSUE THREAD

**Issue by jdanthdavis** [pajlads/DinkPlugin#386]
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

Got an Inquisitor's mace as a drop/new log slot and it did not post in our "Loot" channel but did post in our "Collection Log" channel. I believe this may be an issue with just PNM drops since a Virtus Mask did post in our "Loot" channel the day before.

### Screenshots

![image](https://github.com/pajlads/DinkPlugin/assets/87504521/174436d7-bf13-4a60-a629-76308cf6febc)
![image](https://github.com/pajlads/DinkPlugin/assets/87504521/70455a95-d4cd-41f7-8cc1-30fa9abc56d5)

### Runelite Logs

[client.log](https://github.com/pajlads/DinkPlugin/files/13629873/client.log)

### Runelite Version

1.10.17.2

**Comment by Felanbird** [comment]
It's because of https://github.com/runelite/runelite/issues/16943 - not something we can fix on our own

**Comment by jdanthdavis** [comment]
> It's because of [runelite/runelite#16943](https://github.com/runelite/runelite/issues/16943) - not something we can fix on our own

Thanks for the quick reply!

**Comment by iProdigy** [comment]
Fixed in latest runelite
