### ISSUE TITLE
XP Milestones instead of Virtual Levels for Post 99 XP

### ISSUE THREAD

**Issue by notheowner** [pajlads/DinkPlugin#399]
### Checklist

- [X] I've checked the `Unreleased` section of the [changelog](https://github.com/pajlads/DinkPlugin/blob/master/CHANGELOG.md) for newly added features that sound like my suggestion.
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking suggestions.

### Describe your Suggestion

Since virtual levels are just... virtual.
XP milestones feel more meaningfull after 99 in a skill.
Similar to how Clans in game have Post-99 XP broadcast intervals 
![image](https://github.com/pajlads/DinkPlugin/assets/86596679/d701f8ff-c13e-4116-91ab-56e14d73d010)
The clan broadcast follows this format: $rsn has reached 50,000,000 XP in $skill .
The interval value can be customizable to someone's liking.
Since others might like virtual levels instead, could be as a switch between the two options.

**Comment by iProdigy** [comment]
Good suggestion - will likely require some refactoring of the notifier and a separate metadata structure
