### ISSUE TITLE
Loot -> PVP loot

### ISSUE THREAD

**Issue by Plokstainis** [pajlads/DinkPlugin#403]
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

Hey, we have been testing new "Dink" plugins "Loot" feature "send pk loot to PK URL" and it works as it supposed to be, does the job, but I think we met problem, where it tracks value of single item in the "loot chest" rather than whole chest value, where if you put values like this: for 1m and if the chest has key for 10m total value, but no single item worth 1m+, It doesnt pop out in discord.
Would be awesome if loot keys would be checked as total value, not per single item when it gets opened.

### Screenshots

![image](https://github.com/pajlads/DinkPlugin/assets/150721128/ea8a8802-ca12-490b-aa5c-c768f1a732e1)

### Runelite Logs

.

### Runelite Version

1.10.18.2

**Comment by Plokstainis** [comment]
I see this discussion going very well, we need this! :D

**Comment by iProdigy** [comment]
we (maintainers) have already discussed this request in another channel - just haven't reached a consensus yet on the best solution (as there are multiple ways to accommodate this use case)

**Comment by pajlada** [comment]
@Plokstainis Our current idea is to make loot keys an exception, where they will use the combined value of all items in the key rather than individual items in the key. There would be no extra setting necessary for this, and it would just be mentioned in the "Min Loot value" setting tooltip instead. Does that sound reasonable?

**Comment by Plokstainis** [comment]
I think thats exactly what we need, ant your explanation sounds perfect to me.
