### ISSUE TITLE
Import Command Does Not Update Safe Death Exceptions

### ISSUE THREAD

**Issue by jdanthdavis** [pajlads/DinkPlugin#405]
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

When using the ::dinkimport all command, the "Safe Exceptions" section of Deaths does not update. Here is the deathSafeExceptions obj from our import file - "deathSafeExceptions":["JAD_CHALLENGES","INFERNO","TOB","FIGHT_CAVE","TOA","COX"] if you'd like the whole config file please PM me.

### Screenshots

![death_settings](https://github.com/pajlads/DinkPlugin/assets/87504521/e8b5804c-b7ff-4f9b-bcd6-e172408aae78)
![dink_import_msg](https://github.com/pajlads/DinkPlugin/assets/87504521/39c03848-4b68-41e4-b9a1-1927cb8b28f1)

### Runelite Logs

[launcher.log](https://github.com/pajlads/DinkPlugin/files/13922395/launcher.log)
[client.log](https://github.com/pajlads/DinkPlugin/files/13922397/client.log)

### Runelite Version

1.10.19

**Comment by iProdigy** [comment]
The plugin hub version of Dink now has been updated with this patched
