### ISSUE TITLE
Multiple Webhooks

### ISSUE THREAD

**Issue by cetraben** [pajlads/DinkPlugin#434]
### Checklist

- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking suggestions.
- [X] I've checked the `Unreleased` section of the [changelog](https://github.com/pajlads/DinkPlugin/blob/master/CHANGELOG.md) for newly added features that sound like my suggestion.

### Describe your Suggestion

Would like the option to input multiple webhook URLs so that accolades can be sent to multiple servers.

### Reasoning

Would like to use this functionality in multiple servers :)

**Comment by pajlada** [comment]
This can be done right now by separate your webhooks with newlines.
For example, in your "Primary Webhook URLs" you would include the following:
```
https://discord.com/api/webhooks/1234/webhook1
https://discord.com/api/webhooks/1234/webhook2
```
and upon a notification being fired, it would send the notification both webhook1 and webhook2
