### ISSUE TITLE
Allow multiple webhook configurations for different sets of characters/RSNs 

### ISSUE THREAD

**Issue by eganjs** [pajlads/DinkPlugin#438]
### Checklist

- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking suggestions.
- [X] I've checked the `Unreleased` section of the [changelog](https://github.com/pajlads/DinkPlugin/blob/master/CHANGELOG.md) for newly added features that sound like my suggestion.

### Describe your Suggestion

I would like to send notifications for my GIM to a different webhook.

More general this could be formulated as I would like to decide which webhooks to send notifications to based on a list of allowed RSNs that is associated with each.

The main issue I can think of would be incompatiblity with the `Webhook Overrides` section. In order to maintain compatibility with that I would suggest an alternative that would be implementing a number of config sections (something like 3) that each include `Webhook`, `Webhook Overrides` and `Filtered RSN` properties. This would allow multiple parallel configurations that could be processed on the buliding of a message.

Ideally the outcome would be being able to configure multiple webhooks, each with a list of allowed/denied RSNs, that would send notifications to each webhook based on the RSN filters.

### Reasoning

- I have friends who I play with generally and I send notifications about my main to a shared discord server.
- I am playing a GIM and the group has it's own server, I would like to send notifications about that to the GIM webhook seperately as it is intended for the GIM only.
- I think this builds on top of the webhook override feature and would allow creating configurations that only send one (or more) notification types to a specific webhook e.g. I might enable deaths, but only want to send that to my GIM (using the primary webhook), not my main (by only specifying overrides for the notifcations I want to send).

**Comment by iProdigy** [comment]
I'd suggest leveraging runelite's profiles feature so you have different plugin configurations that you can (manually) switch between (e.g., when switching characters)

**Comment by eganjs** [comment]
I understand where you're coming from but while that may work well initially, I think it would become troublesome after a little while because as you tweak settings for other plugins, eventually you'll get significant drift between your profiles and while you can re-copy and then change the settings again, it's would be significant overhead to maintain. Although it would bring some complexity, I think it would fit much better into the plugin itself.

**Comment by pajlada** [comment]
Could we perhaps leverage our export/import system to make this feasible? I don't want to implement a full on profile system

**Comment by eganjs** [comment]
Could I ask what you mean by import/export system? Is it the same kinda of system as ground markers uses? i.e. using the copy paste buffer with the JSON format

**Comment by pajlada** [comment]
> Could I ask what you mean by import/export system? Is it the same kinda of system as ground markers uses? i.e. using the copy paste buffer with the JSON format

Exactly, you can read more about it in our readme https://github.com/pajlads/DinkPlugin?tab=readme-ov-file#import-configuration-via-dinkimport
I'm not 100% sure it's a good solution for your use case, but I think it's a good start, and we might be able to extend the functionality a bit more to make it a good solution for your use case.

**Comment by APKiwi** [comment]
You could consider using the plugin "Plugin Presets"

![image](https://github.com/pajlads/DinkPlugin/assets/13660274/394edadf-aca6-4436-970e-5d3b494be22d)
https://runelite.net/plugin-hub/show/plugin-presets

The plugin allows you to configure plugin settings for one, few or many plugins, and more granular than that only specific settings within the plugins. This allows you to have a consistent "overall" profile, and have toggles for various sub settings within plugins, this is a magnitude more powerful than the runelite plugin settings.

A quick example; I have made a preset called "GIM" and this preset only has the plugin Dink included, but only the webhook setting. You could of course include more dink settings to fine tune your GIM output (loot threshold, etc), and even include other plugins/settings to toggle on when you are playing your GIM. Hope this helps.

![image](https://github.com/pajlads/DinkPlugin/assets/13660274/1ac7767f-5645-4180-958e-f140a0e90b51)

**Comment by iProdigy** [comment]
Closing in favor of the above solutions as a full profile system is out of scope for dink to implement
