### ISSUE TITLE
Loot: Have rarity override respect denylist

### ISSUE THREAD

**Issue by Raddipple** [pajlads/DinkPlugin#446]
### Checklist

- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking suggestions.
- [X] I've checked the `Unreleased` section of the [changelog](https://github.com/pajlads/DinkPlugin/blob/master/CHANGELOG.md) for newly added features that sound like my suggestion.

### Describe your Suggestion

No longer sends notifications for filtered items just because they're rare.

### Reasoning

Enemy loot tables are a lot of the time filled with rare, but otherwise uninteresting seeds/herbs

**Comment by Felanbird** [comment]
it's probably a bug that it doesn't already do that

**Comment by Raddipple** [comment]
Thought so, but can never be too sure
