### ISSUE TITLE
The embed footer text and icon are reset to default upon Runelite re-load

### ISSUE THREAD

**Issue by Brettyoke49** [pajlads/DinkPlugin#453]
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

I don't want anything in the "Embed footer text" and "Embed footer icon" fields within the advanced options.

I can clear them out to leave an empty box, and it works, until I close Runelite. The next time I reload Runelite, those fields are set back to their default ("Powered by Dink" and the dink icon).

### Runelite Logs

N/A

### Runelite Version

1.10.26.1

**Comment by pajlada** [comment]
I can reproduce this
For now, you can set them to something other than an empty string (e.g. a single space) and that should prevent it from being reset.

**Comment by Mm2PL** [comment]
Can reproduce. What's weird is that this seems to be something related to RuneLite's implementation of default setting values. We don't have code that resets this to defaults.
