### ISSUE TITLE
Loot Key (when open chest) Screenshot

### ISSUE THREAD

**Issue by krisped992** [pajlads/DinkPlugin#456]
### Checklist

- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking suggestions.
- [X] I've checked the `Unreleased` section of the [changelog](https://github.com/pajlads/DinkPlugin/blob/master/CHANGELOG.md) for newly added features that sound like my suggestion.

### Describe your Suggestion

Send screenshot of loot key loot in the chest to a disc channel of your choice. 

### Reasoning

This will be nice for sharing loot with clan members in the discord channel if loot is over X gp.

**Comment by Felanbird** [comment]
This is already a feature, apart of the `Loot` section.
