### ISSUE TITLE
Add Option to Push Events +Types to custom endpoint

### ISSUE THREAD

**Issue by MatthewLoller** [pajlads/DinkPlugin#457]
### Checklist

- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking suggestions.
- [X] I've checked the `Unreleased` section of the [changelog](https://github.com/pajlads/DinkPlugin/blob/master/CHANGELOG.md) for newly added features that sound like my suggestion.

### Describe your Suggestion

Add field to enter in a custom endpoint to post data to.

Under advanced: 'custom event api url' or something. 

POST {{CUSTOMURL}}
{
type: death,
...data
}

### Reasoning

I'd like to be able to store all this data in a db to create monthly reports for anyone in my clan that use this plugin :p

Its an amazing plugin btw! TYSM to all maintainers

**Comment by iProdigy** [comment]
Your custom url can simply be added to the existing webhook config box; we support arbitrarily many URLs (on separate lines)

If this doesn't work for your use case, could you please clarify why?

**Comment by MatthewLoller** [comment]
Ill give this a shot and report back!

**Comment by iProdigy** [comment]
Sounds good! These [docs](https://github.com/pajlads/DinkPlugin/blob/master/docs/json-examples.md#structure) should also be helpful as you write your parser

**Comment by MatthewLoller** [comment]
This is exactly what I needed, its awesome that you guys already have support for it. After a bit of messing with fastify I was able to get the JSON object out of the multipart. 

Thanks for the concise thoughtful replies!
