### ISSUE TITLE
Banned member notifications

### ISSUE THREAD

**Issue by 1000-Ways** [pajlads/DinkPlugin#468]
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

In the event that a member is banned from our group and has dink set up how do I make it to where their  Dink notifications will not show in our discord? 

### Runelite Logs

na

### Runelite Version

1.10.28

**Comment by Mm2PL** [comment]
You need to invalidate your discord webhook. Discord has an option to regenerate the webhook pretty sure. You will need to give all non-banned members the new webhook.

**Comment by Felanbird** [comment]
As Mm2PL said regeneration is really your only reactive way, Discord's webhook system is not really made for a world where users with the URL are suddenly not allowed to have it.
