### ISSUE TITLE
Corrupted Gauntlet Reported as Regular Gauntlet

### ISSUE THREAD

**Issue by ajhakra** [pajlads/DinkPlugin#469]
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

As the title says, upon completion of a Corrupted Gauntlet, Dink sees the chest loot as the regular Gauntlet and displays an incorrect KC.

### Screenshots

![NVIDIA_Share_MbGBr6IHjN](https://github.com/pajlads/DinkPlugin/assets/21299867/253a6b60-c127-4e93-b1d8-24a866a110f5)
![Discord_ULK2xqzAKi](https://github.com/pajlads/DinkPlugin/assets/21299867/4aa46499-a346-4eb7-bc6d-4c8684ceb0fa)

### Runelite Logs

N/A

### Runelite Version

1.10.28.1

**Comment by iProdigy** [comment]
Technically this is a bug with RuneLite's loot tracker but we can investigate a workaround

**Comment by ajhakra** [comment]
Ahh my bad, will wait for that to be fixed then :)  Thanks for the speedy reply though!

**Comment by iProdigy** [comment]
On RL's side: https://github.com/runelite/runelite/pull/13849

Should be easy enough to fix on our end though
