### ISSUE TITLE
Death to "Doom" modifier in Fortis Colosseum does not trigger Death screenshot

### ISSUE THREAD

**Issue by Septem151** [pajlads/DinkPlugin#472]
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

Dying to doom stacks in Fortis Colosseum does not trigger Dink to post a death screenshot.

### Runelite Logs

[client.log](https://github.com/pajlads/DinkPlugin/files/15278030/client.log)

### Runelite Version

1.10.28.1

**Comment by Felanbird** [comment]
Do you mind testing if the `Screenshot` plugin's death screenshot works on a doom death? 
I'd be interested if this is just an issue that RuneLite doesn't recognize a doom death either.

**Comment by Septem151** [comment]
Interestingly, RuneLite's Screenshot plugin doesn't recognize Doom deaths either.

**Comment by Felanbird** [comment]
@Septem151 Does doom _just_ kill you instead of setting you to 0 hp?
