### ISSUE TITLE
BA Queen Kills for the `KILL_COUNT` notifier are sent as 0 for most users

### ISSUE THREAD

**Issue by APKiwi** [pajlads/DinkPlugin#496]
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

For 4/5 of our Dink users we are getting a `0` value for `count` on the extra JSON information on every kill (5+)

eg. `Extra: { boss: 'Penance Queen', count: 0, gameMessage: 'The Queen is dead!' }`

Not sure what other information to provide - the user who has successful messages has the same config. Additionally, no other bosses have this problem

### Screenshots

![image](https://github.com/pajlads/DinkPlugin/assets/13660274/8fd03c12-2177-4e25-954c-d4bdf4abc16b)

### Runelite Logs

Only logs at the time are:
```
2024-06-16 19:46:55 [Client] INFO  c.herblorerecipes.cache.TooltipCache - Tooltip cache was loaded in 5.3692ms.
2024-06-16 19:50:44 [Client] INFO  c.herblorerecipes.cache.TooltipCache - Tooltip cache was loaded in 2.0179ms.
2024-06-16 19:52:32 [Client] INFO  c.herblorerecipes.cache.TooltipCache - Tooltip cache was loaded in 1.9593ms.
```

### Runelite Version

1.10.32

**Comment by APKiwi** [comment]
Example user who has success:
```
16/06 19:50: Player_Name:  Pyro Chi
16/06 19:50: Group name:  undefined
16/06 19:50: Account_Type:   IRONMAN
16/06 19:50: Extra: { boss: 'Penance Queen', count: 22, gameMessage: 'The Queen is dead!' }
```

**Comment by pajlada** [comment]
The BA Queen Kills KC is actually BA High gambles, so the user who have 0 KC, have 0 high gambles

**Comment by Felanbird** [comment]
https://github.com/pajlads/DinkPlugin/blob/9d51ca996a53d67cb2d244a5c86a27405b2e6ed3/docs/json-examples.md?plain=1#L328

**Comment by APKiwi** [comment]
Ah, okay, thank you for the clarification. I'll look at keeping track of this server-side.

**Comment by iProdigy** [comment]
for dink to send true ba kc, we'd need to see changes from runelite or jagex; closing
