### ISSUE TITLE
Require both rarity and value

### ISSUE THREAD

**Issue by TomBoj** [pajlads/DinkPlugin#498]
### Checklist

- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking suggestions.
- [X] I've checked the `Unreleased` section of the [changelog](https://github.com/pajlads/DinkPlugin/blob/master/CHANGELOG.md) for newly added features that sound like my suggestion.

### Describe your Suggestion

It would be useful to be able to only send loot notifications if both the rarity and value thresholds are met.
This was a feature in the **discord-rare-drop-notifier** plugin
![image](https://github.com/pajlads/DinkPlugin/assets/7304411/82714cf8-00d6-4c35-81b8-4033d02b3429)

Apologies if this is already supported, I could not find a way to do it

### Reasoning

It would save having to add a lot of items to the Denylist in the case of getting expensive but common loot. Similarly if you have the rarity override on, but get something rare and worthless

**Comment by iProdigy** [comment]
With this setting enabled, would it be reasonable to have to allowlist certain rare untradeable drops that may have a store value below the configured value threshold?

**Comment by TomBoj** [comment]
The current allowlist notifies on items regardless of value already right? So I would imagine it would work the same way with this.

The way I am imagining this would work is when the notifier checks the value is higher than the threshold, it would then just do an additional check against the rarity threshold before sending the message

**Comment by TomBoj** [comment]
Could it be as simple as something like this?

![image](https://github.com/pajlads/DinkPlugin/assets/7304411/13783e31-6bb0-4502-a509-a18540468946)

I'm not familiar with this code, so I could be way off

**Comment by TomBoj** [comment]
> With this setting enabled, would it be reasonable to have to allowlist certain rare untradeable drops that may have a store value below the configured value threshold?

hmm, I guess this may just be a limitation of using this option. Unless there is some way to identify untradeables, and some other setting associated with that

**Comment by iProdigy** [comment]
> Could it be as simple as something like this?

unfortunately it's a bit more complicated (as you can see in the PR)

&nbsp;

> hmm, I guess this may just be a limitation of using this option. Unless there is some way to identify untradeables, and some other setting associated with that

we theoretically could identify items that are not traded on the GE, but I want to avoid settings proliferation (and the code is complicated enough without that customization)

in general, there are likely more rare untradeable items with low store value that shouldn't be dinked (relative to those that should), so the allowlist approach should be fine

**Comment by TomBoj** [comment]
yeah sounds sensible, thanks for taking a look at this!
