### ISSUE TITLE
Webhooks are delayed + profiles disappear

### ISSUE THREAD

**Issue by Yoface640** [pajlads/DinkPlugin#521]
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

When dying or getting a drop, webhooks are delayed and the profile tab disappears until the webhook is actually sent at which point they reeappar. Other people sending to the same webhook do not have this issue. Problem does not occur when Dink is off.

### Screenshots

![profilestabafterdeath](https://github.com/user-attachments/assets/1c2f0c05-2949-4b3c-835a-e8aa4389639e)
![image](https://github.com/user-attachments/assets/10eab1df-26e1-4ab9-9f26-61859ea1cd96)
![image](https://github.com/user-attachments/assets/84fa783d-b82a-4084-b26f-53526864ea6e)

### Runelite Logs

[client.log](https://github.com/user-attachments/files/16646485/client.log)

### Runelite Version

1.10.36.1

**Comment by pajlada** [comment]
It looks to me like the network request times out, how this would do anything with the profiles page is beyond me though. Maybe unrelated to Dink but related to the NullPointerException further up in the logs?
iProdigy might have a better idea

**Comment by iProdigy** [comment]
In Dink's advanced settings, what is your `Image Upload Timeout` set to? Also what's your upload speed? the error suggests a network issue rather than a dink bug (but you could reduce the `Screenshot Scale` if your network is weak so less data needs to be uploaded)

**Comment by Yoface640** [comment]
30s, it does go away sometimes and when using a vpn to play goes away completely. Don't mind the delay just don't want it affecting my other plugins such as !pb or !layout in COX. Upload speed is 
![image](https://github.com/user-attachments/assets/f9c01668-ec5d-42d5-8fef-edd9da0d197a)

**Comment by Felanbird** [comment]
Can you type `::dinkexport all` into the in-game chat, 
Go to :wrench: -> 👥 -> click `new profile` - double-click to swap to that new profile, 
Download dink again, `::dinkimport` into chat and see if your issue persists?

> and when using a vpn to play goes away completely

While testing those steps may show that it's a conflict with another plugin, the fact that your issue goes away with a VPN enabled makes me personally think that it's an internet problem, unrelated to a fast speedtest result.

**Comment by Yoface640** [comment]
Yes, issue still occurs on a new profile with only dink enabled.

**Comment by iProdigy** [comment]
I'll have to check runelite's usage of the shared ScheduledExecutorService

For diagnosing the network issue, would be useful to run WinMTR pointed at discord.com (let us know how many hops & whether there's packet loss - dont upload the full output here as it can reveal your IP)

**Comment by iProdigy** [comment]
runelite's [`ProfilePanel`](https://github.com/runelite/runelite/blob/573208d6ed9a2adcddbc86f8327d9a1cd730b3d8/runelite-client/src/main/java/net/runelite/client/plugins/config/ProfilePanel.java) does make heavy use of the shared `ScheduledExecutorService`

dink's http requests are also performed on the same executor, so when your network times-out, it's possible for profile panel actions to be delayed

since your internet is fast, you could reduce the image upload timeout to 10s, so the profile panel loads faster when your internet does have some transient timeout issue
