### ISSUE TITLE
screenshot upscale

### ISSUE THREAD

**Issue by Erutpur** [pajlads/DinkPlugin#522]
### Checklist

- [x] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking suggestions.
- [X] I've checked the `Unreleased` section of the [changelog](https://github.com/pajlads/DinkPlugin/blob/master/CHANGELOG.md) for newly added features that sound like my suggestion.

### Describe your Suggestion

I feel like the send screenshot in discord is way too small. I have tried upscaling and going above 100% but it wont increase in size. Would be really cool for old people if the upload was just a little bit bigger. So i don't have to use magnifying glass to see the screenshot : D

**Comment by pajlada** [comment]
Different elements in the screenshot would benefit from different types of upscaling, us doing a full upscale would most like not look very good. Not completely against this, it's just something I'm not sure will give the results you want

**Comment by Felanbird** [comment]
Do you have any example of discord embeds larger than what we currently use so the image could appear larger? 
The only one I've interacted with does not have any sized images above emoji sized, the increased width just comes from extra info being included.

<details>
<summary>e.g.</summary>

![image](https://github.com/user-attachments/assets/adb480a7-40e2-4e89-9518-e5efff7fdc58)
this has a slightly larger width than we do, but I don't believe even that would give you the outcome you want. 

</details>

**Comment by iProdigy** [comment]
we can't really control how large the screenshot within the embed is

![image](https://github.com/user-attachments/assets/d39f3bed-23ca-4114-8d5e-7b4bb730dbc4)


if you disable rich embeds, it does render a bit larger, but yeah you'll still want to click on the image, press `Open in Browser` to get a larger view (and sometimes discord appends query parameters to the image url that make it smaller, yuo can remove those)

**Comment by iProdigy** [comment]
@Erutpur could you clarify whether you mean the size of the screenshot within the rendered embed, or the size of the screenshot after you click `Open in Browser`?

**Comment by iProdigy** [comment]
If the former, we can't do anything about it
If the latter, feel free to re-open for consideration
