### ISSUE TITLE
Combined Loot and Collection log notifications

### ISSUE THREAD

**Issue by wtffixthis** [pajlads/DinkPlugin#530]
### Checklist

- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking suggestions.
- [X] I've checked the `Unreleased` section of the [changelog](https://github.com/pajlads/DinkPlugin/blob/master/CHANGELOG.md) for newly added features that sound like my suggestion.

### Describe your Suggestion

Is there any way to not get a collection log notification if I am going to get a loot notification? 

### Reasoning

I like getting collection log notifications regardless of their value and also loot notifications of a higher value. When it is a collection log and also over my loot value I get 2 notifications.

**Comment by iProdigy** [comment]
Thanks for the feature request! Unfortunately there are too many complications to pursue this enhancement:

* Depending on the loot source, the loot event may come first or the collection event may come first, so there isn't a single determinate notifier to combine the logic of the other (and I don't want to delay all loot and collection notifications to deduplicate them)
* Non-discord handlers may still expect to observe `LOOT` or `COLLECTION` notification types (or both), so only sending one can be problematic (and I don't want to introduce complexities of domain-specific logic)
* Some users have loot and collection notifications directed at different discord channels (or servers), so they may not want deduplication for all URLs (and we're not in the position to allow url-specific configuration currently)

Please do open additional feature requests as you continue to use dink :)
