### ISSUE TITLE
Plugin now incompatible

### ISSUE THREAD

**Issue by Uutama** [pajlads/DinkPlugin#554]
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

"Plugin is incompatible and requires the author to update it." No longer works after having worked for months. September 22nd it seems to no longer be working.

### Screenshots

![image_2024-09-22_143739139](https://github.com/user-attachments/assets/92c8a89c-20ae-4389-b639-bd738a5f4a82)

### Runelite Logs

[client.log](https://github.com/user-attachments/files/17090828/client.log)

### Runelite Version

1.10.37.2

**Comment by iProdigy** [comment]
Fix was just merged :) https://github.com/runelite/plugin-hub/pull/6631
