### ISSUE TITLE
Death notifier: Include extra information about zone/area the player died in

### ISSUE THREAD

**Issue by pajlada** [pajlads/DinkPlugin#56]
If it's possible to get zone name, it could be used for differing the message if a user dies in NMZ vs in a raid

**Comment by iProdigy** [comment]
For NMZ: `player.getWorldLocation().getPlane() > 0 && client.getMapRegions().length == 1 && client.getMapRegions()[0] == 9033`

For raids: `client.getVarbitValue(Varbits.IN_RAID) == 1`
