### ISSUE TITLE
Add support for migrating config from the Discord Rare Drop Notifier plugin

### ISSUE THREAD

**Issue by pajlada** [pajlads/DinkPlugin#563]
After discussions with the current maintainer of the plugin @BossHuso we'd like to add the ability to migrate the user's plugin config into Dink.

I see this being done with a user command (e.g. `::dinkmigrate`). Name might need to be more specific, or it accepts a parameter, or it popups up a dialog with user choice or something.

Once this is implemented on our end, the Discord Rare Drop Notifier plugin can prompt users to use the command to migrate their config.

Open questions:
Should we remove the config keys from the Discord Rare Drop Notifier plugins after migrating them?

Plugin repo: https://github.com/BossHuso/discord-rare-drop-notificater

**Comment by iProdigy** [comment]
> Should we remove the config keys from the Discord Rare Drop Notifier plugins after migrating them?

This would be too intrusive in my opinion - at most we could disable the plugin post-migration, but it's not worth the technical complexity

&nbsp;

Open question: what syntax should we use to migrate from specific plugins? e.g., `::dinkmigrate bosshuso` or `::dinkmigrate huso` or `::dinkmigrate discord-rare-drop-notificater` or `::dinkmigrate discordraredrop-notifier` (and so on)

**Comment by BossHuso** [comment]
> Open question: what syntax should we use to migrate from specific plugins? e.g., `::dinkmigrate bosshuso` or `::dinkmigrate huso` or `::dinkmigrate discord-rare-drop-notificater` or `::dinkmigrate discordraredrop-notifier` (and so on)

For simplicity I think "huso" should be fine, the latter ones would be more representative but the plugin name is really a.. to write and kinda long ;)

I will test the migration and will start making the required changes on our side.

**Comment by iProdigy** [comment]
right now the PR does `::DinkMigrate DiscordRareDropNotifier` since @Felanbird suggested most users are more familiar with plugin names than authors - but this decision isn't set in stone yet

**Comment by pajlada** [comment]
I'm ok with both being acceptable

**Comment by iProdigy** [comment]
Added alias support so all of these work now: `DiscordRareDropNotifier`, `DiscordRareDropNotificaterPlugin`, `DiscordRareDropNotificater`, `BossHuso`, `Huso`, `Rare` (case insensitive for all, but `DiscordRareDropNotifier` case sensitive is fastest)

**Comment by iProdigy** [comment]
@BossHuso feel free to test the migration using the shadow jar produced by the gradle gh action: https://github.com/pajlads/DinkPlugin/actions/runs/11311758385/artifacts/2049670217

these are the known limitations: https://github.com/pajlads/DinkPlugin/blob/4d84d840e494091e15828dad8222c6dc462a6282/README.md#discord-rare-drop-notifier
