### ISSUE TITLE
Boss kill count messages send inconsistent image

### ISSUE THREAD

**Issue by harbingerofme** [pajlads/DinkPlugin#577]
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

When hitting an interval, randomly an image of the boss will be attached to the message. This does not always get attached, nor is there a way to not send these at all. The size of them is inconsistent as well across different bosses.

### Screenshots

![Screenshot 2024-10-28 124838](https://github.com/user-attachments/assets/2a562f58-09d8-4bbc-9fc7-4044a51a863a)
![Screenshot 2024-10-28 124931](https://github.com/user-attachments/assets/69d7dd08-27a5-45b8-b7d3-0ea69609a720)

### Runelite Logs

[client.log](https://github.com/user-attachments/files/17541865/client.log)

### Runelite Version

1.10.42.1

**Comment by Felanbird** [comment]
Is there an icon in the top right of the first notif? I assume it's discord falling back because the first embed we intend to send is not being sent, and it's falling back to the second one, coming from the wiki link to Kraken. 

Maybe you can also try changing `%BOSS%` in your `notification message` to `<%BOSS%>`? That would work in theory since `<link_here>` is how you send a link on discord without embed.

**Comment by harbingerofme** [comment]
> Is there an icon in the top right of the first notif? I assume it's discord falling back because the first embed we intend to send is not being sent, and it's falling back to the second one, coming from the wiki link to Kraken.
> 

Yes, that one is normal.

> Maybe you can also try changing `%BOSS%` in your `notification message` to `<%BOSS%>`? That would work in theory since `<link_here>` is how you send a link on discord without embed.

For the record, the message previously was `%COUNT% **%BOSS%**!`. Adding brackets completely breaks it.
![Screenshot 2024-10-28 221713](https://github.com/user-attachments/assets/8f808bbc-61d0-408c-ba4e-638b5a24fb8f)

**Comment by harbingerofme** [comment]
Full relevant config

![image](https://github.com/user-attachments/assets/a1097403-de97-43ef-be3a-88bb75896b85)

**Comment by Felanbird** [comment]
> For the record, the message previously was `%COUNT% **%BOSS%**!`. Adding brackets completely breaks it.

heh
