### ISSUE TITLE
How can I debug an issue?

### ISSUE THREAD

**Issue by Deiiv** [pajlads/DinkPlugin#579]
Dink and other discord notifiers stopped working, but I'm not sure why. The issue first started when I had two discord notification plugins running at the same time (discord notifier plugin for my clan, dink for myself), which for some reason led to inconsistent notifications (maybe there are some conflicts, couldn't find any info on this). I uninstalled both, reinstalled dink, which led to dink working but still for only half of the notifications. Eventually, after a few days, I noticed no notifications were coming at all, so I reinstalled dink, reinstalled runelite, and nothing was fixing the issue.

I tried to see if I could find logs for Dink, but the log file had no mentions of notifications or discord or dink in general.

How can I turn on debug logs so I can dig into the issue?

**Comment by Felanbird** [comment]
<https://github.com/runelite/runelite/wiki/RuneLite-Launcher-Configuration> but check the `debug` box instead of `safe mode`

not sure if our logging is verbose enough for your issue but good luck

**Comment by iProdigy** [comment]
Also could you share the output of `::dinkexport` with us?

And a client log would be nice

**Comment by Deiiv** [comment]
Here's the output of ::dinkexport:

`{"killCountInterval":50,"combatTaskEnabled":false,"gambleRareNotifMessage":"%USERNAME% has received rare loot at gamble count %COUNT%: \n\n%LOOT%","speedrunEnabled":false,"questEnabled":false,"deathNotifMessage":"%USERNAME% has died...","collectionNotifMessage":"%USERNAME% has added %ITEM% to their collection","levelNotifyVirtual":true,"questNotifMessage":"%USERNAME% has completed a quest: %QUEST%","killCountEnabled":false,"slayerNotifMessage":"%USERNAME% has completed a slayer task: %TASK%, getting %POINTS% points and making that %TASKCOUNT% tasks completed","levelInterval":1,"notifyTrades":false,"speedrunMessage":"%USERNAME% has just finished a speedrun of %QUEST% with a time of %TIME% (their PB is %BEST%)","sendDiscordUser":true,"clueSendImage":true,"chatNotifyMessage":"%USERNAME% received a chat message:\n\n```\n%MESSAGE%\n```","slayerEnabled":false,"deathEnabled":false,"combatTaskUnlockMessage":"%USERNAME% has unlocked the rewards for the %COMPLETED% tier, by completing the combat task: %TASK%","deathMinValue":0,"lootIncludeClueScrolls":true,"pkIncludeLocation":true,"lootIcons":false,"lootEnabled":false,"petNotifMessage":"%USERNAME% %GAME_MESSAGE%","nameFilterMode":"DENY","lootRarityThreshold":0,"maxRetries":3,"speedrunPBOnly":true,"embedFooterText":"Powered by Dink","includeLocation":true,"groupStorageNotifyMessage":"%USERNAME% has deposited:\n%DEPOSITED%\n\n%USERNAME% has withdrawn:\n%WITHDRAWN%","deathEmbedProtected":false,"diarySendImage":true,"questSendImage":true,"killCountSendImage":true,"sendGroupIronClanName":true,"speedrunSendImage":true,"lootRarityValueIntersection":false,"levelEnabled":false,"petEnabled":false,"chatMessageTypes":["GAME","COMMAND"],"tradeMinValue":0,"slayerPointThreshold":0,"petSendImage":true,"groupStorageMinValue":0,"embedFooterIcon":"https://github.com/pajlads/DinkPlugin/raw/master/icon.png","killCountInitial":true,"combatTaskSendImage":true,"lootSendImage":true,"pkSendImage":true,"deathNotifPvpEnabled":true,"gambleInterval":100,"combatTaskMessage":"%USERNAME% has completed %TIER% combat task: %TASK%","ignoreSeasonalWorlds":false,"collectionLogEnabled":false,"grandExchangeSendImage":true,"speedrunPBMessage":"%USERNAME% has just beat their personal best in a speedrun of %QUEST% with a time of %TIME%","screenshotHideChat":false,"deathSendImage":true,"lootImageMinValue":0,"diaryMinDifficulty":"EASY","clueMinTier":"BEGINNER","pkNotifyMessage":"%USERNAME% has PK\u0027d %TARGET%","killCountPenanceQueen":true,"baseRetryDelay":2000,"clueImageMinValue":0,"deathIgnoreSafe":true,"levelMinValue":1,"includeClientFrame":false,"levelIntervalOverride":0,"grandExchangeProgressSpacingMinutes":-1,"gambleSendImage":true,"pkEnabled":false,"imageWriteTimeout":30,"gambleNotifMessage":"%USERNAME% has reached %COUNT% high gambles","clueNotifMessage":"%USERNAME% has completed a %CLUE% clue, they have completed %COUNT%.\nThey obtained:\n\n%LOOT%","gambleRareLoot":true,"clueEnabled":false,"clueMinValue":0,"levelSendImage":true,"embedColor":"#FFF40098","deathIgnoredRegions":"123, 456, 789","chatSendImage":true,"groupStorageIncludeClan":true,"pkSkipSafe":true,"levelNotifyCombat":false,"sendClanName":true,"threadNameTemplate":"[%TYPE%] %MESSAGE%","playerLookupService":"OSRS_HISCORE","tradeNotifyMessage":"%USERNAME% traded with %COUNTERPARTY%","lootIncludePlayer":true,"combatTaskMinTier":"EASY","grandExchangeIncludeCancelled":false,"deathSafeExceptions":["FIGHT_CAVE","INFERNO"],"groupStorageSendImage":true,"levelNotifMessage":"%USERNAME% has levelled %SKILL%","killCountBestTimeMessage":"%USERNAME% has defeated %BOSS% with a new personal best time of %TIME% and a completion count of %COUNT%","collectionSendImage":true,"screenshotScale":100,"notifyChat":false,"lootNotifMessage":"%USERNAME% has looted: \n\n%LOOT%\nFrom: %SOURCE%","chatPatterns":"You\u0027ve unlocked an emote: *\nYou\u0027ve completed the * event*\nYou have accepted * into *.\nYou will be logged out in approximately 30 minutes.*\nYou will be logged out in approximately 10 minutes.*\n::TriggerDink\n","diaryEnabled":false,"deathNotifPvpMessage":"%USERNAME% has just been PKed by %PKER% for %VALUELOST% gp...","groupStorageEnabled":false,"diaryMessage":"%USERNAME% has completed the %DIFFICULTY% %AREA% Achievement Diary, for a total of %TOTAL% diaries completed","minLootValue":0,"pkMinValue":0,"notifyGrandExchange":false,"grandExchangeNotifyMessage":"%USERNAME% %TYPE% %ITEM% on the GE","killCountPB":true,"discordRichEmbeds":true,"slayerSendImage":true,"tradeSendImage":true,"grandExchangeMinValue":100000,"xpInterval":5,"clueShowItems":false,"killCountMessage":"%USERNAME% has defeated %BOSS% with a completion count of %COUNT%","groupStorageIncludePrice":true,"pkSkipFriendly":false,"lootRedirectPlayerKill":false,"gambleEnabled":false}`

I'll turn on debug for the next clog drop so I can capture some logs

**Comment by iProdigy** [comment]
@Deiiv you have to go into Dink settings and enable the notifiers you care about - currently they're all disabled

**Comment by Deiiv** [comment]
> @Deiiv you have to go into Dink settings and enable the notifiers you care about - currently they're all disabled

lol! I can't believe I missed that, must have reset when I reinstalled it. Thanks!

**Comment by Deiiv** [comment]
@iProdigy do you know if I can run Dink side by side with this plugin, or would it give issues: https://runelite.net/plugin-hub/show/discord-rare-drop-notificater

This is where my problems originally started, from trying to run both at the same time, I'm just not sure if it would break it again if I did try it

**Comment by iProdigy** [comment]
yes you can run both at the same time - what's your intended use case for doing so? (that plugin author is working with us to direct their users to install dink instead)

**Comment by Deiiv** [comment]
The clan I'm with uses that plugin for tracking clan points based on specific drops, not sure why they use it over Dink, but I don't mind it because I want my own notifications with separate settings vs what the clan needs for the rare drop rewards. I don't think we can choose two separate discord webhook destinations for different options right now in Dink.

**Comment by iProdigy** [comment]
yeah if you want different settings for different urls, using multiple plugins is perfectly fine :+1:
