### ISSUE TITLE
Whitelist from external source such as Google Sheets (clan events such as bingos)

### ISSUE THREAD

**Issue by Nallieheai** [pajlads/DinkPlugin#581]
### Checklist

- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking suggestions.
- [X] I've checked the `Unreleased` section of the [changelog](https://github.com/pajlads/DinkPlugin/blob/master/CHANGELOG.md) for newly added features that sound like my suggestion.

### Describe your Suggestion

It would be nice to allow for an external whitelist, such as a Google Sheet with a column of different items that would be posted and nothing else. Potentially also listing the source of the drop so that for example and Elite Clue dropped from "King Black Dragon" would drop but not an Elite Clue from Kraken or any other source not listed.

The source of the item would not be super critical for the basic functionality but i believe it would be a nice feature to have.

Example: 

![image](https://github.com/user-attachments/assets/f472ee6a-98a6-4785-ac07-d9183d9908f2)

Obviously only 1 item can be list per row and multiple sources can drop it, so splitting on commas, or any other delimiter and then turning it all lowercase and trimming it to make sure nothing funky is happening. If no source is given, post the item no matter what if you receive it from any source.

I know there are limits to how often you can query a Google API key so perhaps limiting it to once per 5 or 10 minutes would be ideal to prevent it sending tons of event each time you hop world or logout trying to avoid a pker and then logging back in 5 seconds later. The list does not really have to update that often since its very unlikely it will be actively changing once an event has started.

### Reasoning

It would be great when organizing larger bingos such as clan vs clan bingos with hundreds of people who need the same whitelist of items that are supposed to post to a specific discord channel for review by the event team.

Then two hours into the bingo one of the moderators notice they made a typo and suddenly everyone have to manually update it. With this feature the event team can simply update the Google Sheet and upon the next login/manual from the user they receive the new list of items.

Ive seen other plugins with similar features such as the Clan Event plugin where they fetch standings from a Google Sheet. But it seems more fitting here because a lot of the time you have a bingo board of items you need to obtain and post to a Discord chat where the event team will verify the screenshot and source.

**Comment by pajlada** [comment]
If you're able to get the data from the google sheet into json (such as with appscript), and you pack that together with the full Dink config, you could achieve this right now with the "Dynamic Config URL" option.

My initial vibe is that we'd prefer that to be used, rather than adding something as platform-locked as google sheet support.
If you need any help achieving this through the "Dynamic Config URL" option we're happy to help

**Comment by Nallieheai** [comment]
> If you're able to get the data from the google sheet into json (such as with appscript), and you pack that together with the other bingo-related Dink config, you could achieve this right now with the "Dynamic Config URL" option.
> 
> My initial vibe is that we'd prefer that to be used, rather than adding something as platform-locked as google sheet support. If you need any help achieving this through the "Dynamic Config URL" option we're happy to help
> 
> For item allowlist from a specific source, that's not something we support. If it's something that would be required, that'd be best as a separate feature request.

Thanks for the reply, i will have a look at that right away!

**Comment by Nallieheai** [comment]
Hello again, i was able to add a list of items to the whitelist field and get all the settings set up as i wanted them. I then exported the file and uploaded it to my web server and made the file accessible and it works like a charm. My friend who is helping me test it was able to get the exact same settings working for him with no effort. This really is all we could have asked for. Thanks for pointing me in the right direction! 

As for the the source of the drop it would be really cool to only post the specific items for specific sources that are "whitelisted" but its not the end of the world if they post from other places as well because it actually says the source in Discord when the image is posted.

In most cases we wont be using generic items such as "Bones" so its very unlikely it will spam a ton, most likely it would overlap in places like a Dragon Axe that can drop from the 3 DKs + Wintertodt. In a skilling bingo for example only the one from Wintertodt would be interesting but its also not that big of a concern if someone would do their DKs task during bingo and pull one as it would be easy to tell the difference as well as seeing the source be posted alongside the item.

We are also having a little bit of a "clan point" system which we manually distribute points to items based on the source, so using the Dragon Axe example again it would be worth more points from Wintertodt than DKs because it way more rare from there. However since the Discord message that is sent says the source of the item im pretty confident we can set up a Discord bot to automate most of this process for us and simply ignore the rest if any slip through.

I am quite new to Dink and it comes with a ton of features which is amazing, for the most part Dynamic Config URL does everything we want and i simply did not realize it could be used like this. Thanks for all your hard work to everyone working on this project!

**Comment by iProdigy** [comment]
You actually could write a custom webhook handler that automates point calculation since the loot notification metadata does have a field for the source: https://github.com/pajlads/DinkPlugin/blob/master/docs/json-examples.md#loot

e.g. you can host it for free with cloudflare workers (and persist the points in their D1 sql product)

here's an example for an unrelated use case: https://gist.github.com/iProdigy/53654691a76679221a74fd442dea068a
