### ISSUE TITLE
Send Current CA Tier & Total Possible CA Points In COMBAT_ACHIEVEMENTS Metadata

### ISSUE THREAD

**Issue by jdanthdavis** [pajlads/DinkPlugin#583]
### Checklist

- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking suggestions.
- [x] I've checked the `Unreleased` section of the [changelog](https://github.com/pajlads/DinkPlugin/blob/master/CHANGELOG.md) for newly added features that sound like my suggestion.

### Describe your Suggestion

Add the user's currently held CA Tier to the metadata when completing a CA task.
```
{
  "content": "%USERNAME% has completed %TIER% combat task: %TASK%",
  "extra": {
    "tier": "GRANDMASTER",
    "task": "Peach Conjurer",
    "taskPoints": 6,
    "totalPoints": 1337,
    "tierProgress": 517,
    "tierTotalPoints": 645, 
    "currentTier": "MASTER" // new addition
  },
  "type": "COMBAT_ACHIEVEMENT"
}
```

Add the grand total of CA points currently achievable to the metadata when completing a CA tier.
```
{
  "content": "%USERNAME% has unlocked the rewards for the %COMPLETED% tier, by completing the combat task: %TASK%",
  "extra": {
    "tier": "GRANDMASTER",
    "task": "Peach Conjurer",
    "taskPoints": 6,
    "totalPoints": 1465,
    "tierProgress": 0,
    "tierTotalPoints": 540,
    "totalPossiblePoints: 2445, // new addition
    "justCompletedTier": "MASTER"
  },
  "type": "COMBAT_ACHIEVEMENT"
}
```

### Reasoning

Being able to know the user's current CA tier and the possible total points achievable (currently 2445) would be incredibly useful. I initially thought of hard-coding these values but since they're ever-changing it would be much easier for me to just have Dink pass this information along instead of me having to define the breaks for each CA tier and update the total possible points.

**Comment by iProdigy** [comment]
I can PR this tonight, or did you want to give it a shot?

**Comment by Felanbird** [comment]
if you want to give it a shot the varbits necessary are:
`4132` points needed for easy
`10660` points needed for medium
`10661` points needed for hard
`14812` points needed for elite
`14813` points need for master
`14814` points needed for grandmaster/total points

probably have to do some math to figure out where current tier is, i don't see a 1,2,3,4,5,6 valued varbit in the script

**Comment by iProdigy** [comment]
we actually already have the varbits: https://github.com/pajlads/DinkPlugin/blob/master/src/main/java/dinkplugin/notifiers/CombatTaskNotifier.java#L149-L156

and know the current tier (it's just not sent in metadata unless the tier changed): https://github.com/pajlads/DinkPlugin/blob/master/src/main/java/dinkplugin/notifiers/CombatTaskNotifier.java#L89

**Comment by jdanthdavis** [comment]
Yeah I'd love to give this a go! Thanks for the offer. I'll take a look tomorrow :)

**Comment by iProdigy** [comment]
> Yeah I'd love to give this a go! Thanks for the offer. I'll take a look tomorrow 🙂

Sounds good, let us know if you need any assistance

e.g., to better understand `cumulativeUnlockPoints`: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/NavigableMap.html

**Comment by iProdigy** [comment]
I forgot to mention: don't feel obligated to update the test suite, we can take care of that part
alternatively if you got more busy, let us know if you'd rather us handle the whole pr
@jdanthdavis

**Comment by jdanthdavis** [comment]
> I forgot to mention: don't feel obligated to update the test suite, we can take care of that part alternatively if you got more busy, let us know if you'd rather us handle the whole pr @jdanthdavis

Sorry about the delay! Just got my env setup and currently working on it. I've never wrote any test cases in Java so if you don't mind I'd like to take a stab at it and get your review.

**Comment by jdanthdavis** [comment]
@iProdigy What would be the best way to test these changes? Am I able to actually hit a `url` locally without having to complete a task in-game?

**Comment by iProdigy** [comment]
No worries on the delay - it's your feature request so take as much time as you want

For the test setup that you've probably already figured out: https://github.com/pajlads/DinkPlugin/blob/master/docs/TESTING.md

To fix the test errors, you'll want to update this file: https://github.com/jdanthdavis/DinkPlugin/blob/feature/add-ca-notifer-data/src/test/java/dinkplugin/notifiers/CombatTaskNotifierTest.java

**Comment by jdanthdavis** [comment]
> For the test setup that you've probably already figured out: https://github.com/pajlads/DinkPlugin/blob/master/docs/TESTING.md
> 
> To fix the test errors, you'll want to update this file: https://github.com/jdanthdavis/DinkPlugin/blob/feature/add-ca-notifer-data/src/test/java/dinkplugin/notifiers/CombatTaskNotifierTest.java

Thanks for the docs, I'll attempt to get these sorted later tonight and throw them in #586.

I do have another question. Why is `GRANDMASTER_TOTAL_POINTS_ID` 14814? Obviously, you're not using the actual in-game point value and I can see the math you're doing with `CUM_POINTS_VARBIT_BY_TIER` but I'm not wrapping my head around why these points are used to determine the thresholds.

**Comment by jdanthdavis** [comment]
> That ID is defined by jagex & somewhat arbitrary - to get the value associated with the ID see [#586 (comment)](https://github.com/pajlads/DinkPlugin/pull/586#discussion_r1835052501)

I think I understand. You aren't defining thresholds you're just getting the IDs there?

**Comment by iProdigy** [comment]
Yeah we don't hardcode the thresholds, instead we pull the threshold values from the game using those static IDs
