### ISSUE TITLE
Loot notifications sending incorrect/wrong Araxxor loot

### ISSUE THREAD

**Issue by brkyup** [pajlads/DinkPlugin#584]
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

Dink is sending notifications for loot from Araxxor that it does not drop

### Screenshots

![image](https://github.com/user-attachments/assets/736300a5-7a68-44d7-9f35-36d9b2e3aa80)
![image](https://github.com/user-attachments/assets/81aeffba-6f80-4f1b-92e6-c9a29047828b)
![image](https://github.com/user-attachments/assets/eb0344d0-d1c8-4ec1-9b74-13892fcfd484)

### Runelite Logs

[client.log](https://github.com/user-attachments/files/17671901/client.log)

### Runelite Version

1.10.43

**Comment by iProdigy** [comment]
This is a shortcoming in runelite's loot tracker; see https://github.com/runelite/runelite/issues/18242#issuecomment-2336027507
