### ISSUE TITLE
Use Hiscore Sprites For Kill Count Notifier

### ISSUE THREAD

**Issue by jdanthdavis** [pajlads/DinkPlugin#610]
### Checklist

- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking suggestions.
- [X] I've checked the `Unreleased` section of the [changelog](https://github.com/pajlads/DinkPlugin/blob/master/CHANGELOG.md) for newly added features that sound like my suggestion.

### Describe your Suggestion

Instead of using the default Slayer Gem icon, use the boss's hiscore icon.

From the little bit of research I did it looks like all the new icons are in the cache and I was able to locate all the sprites from [melkypie/sprite-exporter.](https://github.com/melkypie/sprite-exporter)

Edit: If this does seem like something the Dink team wanted; I'd love to help out creating this feature 🙂

### Example
![example](https://github.com/user-attachments/assets/6fd7d0ab-2971-40bd-8db6-c62bcc11aaf5)

### Reasoning

It would give a bit more spice to each embed. It would also be a bit easier identifying what the notification is about at a glance with an icon of that boss.

**Comment by iProdigy** [comment]
while certain images may be in the cache, we don't want to have to upload those images from the client for notifications - so we limit ourselves to static images from the osrs wiki cdn

it'd be easy to include an image of the npc for the thumbnail, but the heterogeneous sizing (and large images) may make it look weird

**Comment by iProdigy** [comment]
the wiki doesn't appear to have a consistent file nomenclature for those boss hiscore images, so closing as not planned for now.
