### ISSUE TITLE
Duplicate notifications sent when specifying a high retry count

### ISSUE THREAD

**Issue by Deiiv** [pajlads/DinkPlugin#624]
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

I had to set a high retry count/timeout (it's excessive, but I have no way to pinpoint an accurate value at the moment) in order to consistently get notifications. Without it, notifications didn't go through (likely something to do with my wifi or discord, not sure yet), but with the timeout values as they are things are "working". The problem I'm facing now is that it sends the notification 3x times, and this happened twice today (attached screenshots below).

The error Dink keeps getting is the following (also attached client.log below with more info):

`2024-12-02 09:44:47 EST [OkHttp https://discord.com/...] WARN  d.message.DiscordMessageHandler - There was an error sending the webhook message
okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR`

I believe this is the error that is causing me to set a higher retry, but I'm not sure, if anyone knows how to solve this error then maybe I can just go back to the default retry timeout settings. Otherwise, whenever this error (unless it's something else) pops up, Dink keeps retrying even though it might have gone through successfully. This might be fixable through changing how Dink waits for a response, or it might be something I need to change on my retry/timeout settings, I'm open to suggestions.

### Screenshots

![image](https://github.com/user-attachments/assets/6adf189a-3e99-4b37-a14f-8cc6fbd43189)

![image](https://github.com/user-attachments/assets/1c3b23fe-61cf-4618-975c-d52b673c0776)

### Runelite Logs

[client.log](https://github.com/user-attachments/files/17981956/client.log)

### Runelite Version

1.10.45

**Comment by Deiiv** [comment]
Upload speed is pretty garbage haha need to see why that is:

![image](https://github.com/user-attachments/assets/fad6ec45-1eaf-4bf5-9397-c1a201730c52)

Not using anything in between runelite and discord, just the webhook url.

**Comment by iProdigy** [comment]
With that internet speed, I'd recommend disabling screenshots for all notifiers

**Comment by Deiiv** [comment]
Thanks for pointing me down the right rabbit hole! The issue here was definitely my upload speed (although it sending multiple times is still weird).

Ended up on a hunt to figure out the issue with my network driver and sorted it out, should be good to go now, I'll reset to the default retry values
