### ISSUE TITLE
[Chat] Send source user's rank with clan chat messages

### ISSUE THREAD

**Issue by tmgrhm** [pajlads/DinkPlugin#633]
### Checklist

- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking suggestions.
- [X] I've checked the `Unreleased` section of the [changelog](https://github.com/pajlads/DinkPlugin/blob/master/CHANGELOG.md) for newly added features that sound like my suggestion.

### Describe your Suggestion

Would there be any interest in adding the `source` user's rank as a field in `extra` for `CLAN_CHAT` messages (and I suppose Chat Channel messages too)?  

(I've found another plugin which does this, "Clan Chat Webhook" — e.g. `"clanTitle":"TzTok"` — but I prefer Dink for a few reasons. Most importantly, that plugin doesn't convey join/leave messages, which Dink does.)

### Reasoning

I'd simply like to be able to ignore messages from Guests while tracking clan member activity which our mods then use to purge inactive members.  
I can imagine this having wider practical uses too, although I imagine they are quite niche so I can understand the answer being "no, not worth the time and extra data".

**Comment by iProdigy** [comment]
> Would there be any interest in adding the `source` user's rank as a field in `extra` for `CLAN_CHAT` messages

Yeah I can see that field being useful and it's not too complicated to include!

>  (and I suppose Chat Channel messages too)?

Right now #635 only adds the field for clan messages (but not clan notifications) - we can revisit this if you have a use case (currently it's omitted as a performance optimization)

> I'd simply like to be able to ignore messages from Guests

isn't this already possible by checking if the type is `CLAN_GUEST_CHAT`?

**Comment by tmgrhm** [comment]
>isn't this already possible by checking if the type is `CLAN_GUEST_CHAT`?

I actually wasn't aware that was a thing, thanks, but I'm already only reading `CLAN_CHAT` and `CLAN_MESSAGE`s and discarding everything else. The problem I'm having then is that `CLAN_MESSAGE`s from guests are indistinguishable from members.  
With _Show join/leave_ enabled in the _Chat Channels_ plugin (and maybe by default? Idk) you receive a `CLAN_MESSAGE` every time someone leaves or joins ("_x_ has joined."), which obviously happens a lot more frequently than someone triggering a broadcast or speaking, making it a more reliable method for tracking when someone was last active. 

Because I can't tell who's a member and who's not from the `CLAN_MESSAGE` data, there's a fair few redundant rows in my clan "member" activity tracker.  It's not the end of the world, so like I say if the performance overhead is relatively significant then I totally understand the answer being "no", but it would be nice to be able to just ignore those or maybe track guest data separately, as well as being able to log all users' ranks alongside activity to help mods weigh up who should be removed to make room for new faces.

(I am aware that using dink here is a bit of a bodge job and the ideal solution is to have a purpose-built RuneLite plugin to keep watch over the clan members list and send the required data by webhook, without having to wait and listen for join/leave, broadcasts, and chat, but I'm not familiar with plugin dev and while doing something else with dink I realised this could do pretty much the same job with very little effort.  
Surprisingly, such a plugin doesn't exist already from what I can tell. There are similar plugins but not one which will record the necessary data _and_ send it to a custom webhook — one I've found only records it locally and another requires use of a third-party service)

**Comment by iProdigy** [comment]
Could you double check guests are triggering `CLAN_MESSAGE`? In theory they should emit `CLAN_GUEST_MESSAGE`

also the performance penalty is just a $O(n)$ search, which isn't large in the context of the preceding regex checks, so that's not a first-order concern

**Comment by tmgrhm** [comment]
Yeah I tested it before leaving my last comment. If they type a message it's `CLAN_GUEST_CHAT` but if it's a join/leave it's still just `CLAN_MESSAGE`.

```{"type":"CHAT","playerName":"me","accountType":"IRONMAN","dinkAccountHash":"xxx","clanName":"xxx","seasonalWorld":false,"world":508,"regionId":4922,"extra":{"type":"CLAN_MESSAGE","source":"","message":"GUEST has joined."},"discordUser":{"id":"xxx","name":"meDiscord","avatarHash":"xxx"},"embeds":[{"title":"Chat Notification","description":"Me received a chat message:\n\n`\nGUEST has joined.\n`","author":{"name":"Me","icon_url":"https://oldschool.runescape.wiki/images/Ironman_chat_badge.png","url":"https://secure.runescape.com/m\u003dhiscore_oldschool/hiscorepersonal?user1\u003dMe"},"color":15990936,"thumbnail":{"url":"https://oldschool.runescape.wiki/images/Toggle_Chat_effects.png"},"fields":[],"footer":{"text":"footer."},"timestamp":"2024-12-29T16:13:43.509835Z"}]}```

If it were `CLAN_GUEST_MESSAGE` I wouldn't be seeing it as the first line of my `doPOST()` function returns if `extra.type` isn't `CLAN_MESSAGE` or `CLAN_CHAT`

I have come up with a manual workaround: export the clan members data with the _Clanmate Export_ plugin, which exports the rsn, rank, and join date as a json object for each member, then a script adds that to the members list which dink is hooked up to. Anyone who isn't a member doesn't have either of those values by default, so you can imply they're either a guest or a new member since the last manual import of that data. But again, being able to automate the rank at least via dink would be a nice to have.

**Comment by iProdigy** [comment]
thanks - that looks like a bug on jagex's end

the problem with `CLAN_MESSAGE`/`CLAN_GUEST_MESSAGE` is the `source` is absent so we'd have to do some guesswork as to which player is being discussed. typically the name is the first thing in the `message`, but folks can have spaces in their name so it's not as trivial as a string split.

i agree that repeatedly doing manual clan exports is annoying - instead you could store RSNs and associated title in a database as you receive `CLAN_CHAT`/`CLAN_GUEST_CHAT` (but still this assumes people will eventually chat).

i'll consider adding `_ has joined.` as a special case where we do include the clan title upon `CLAN_MESSAGE`, so you wouldn't need to setup a database or do manual exports

**Comment by tmgrhm** [comment]
Yeah, `source` not being the rsn of the relevant user struck me as weird — but that's coming from Jagex and not dink?

I resorted to a series of regex patterns of common broadcast messages to try and extract the RSN — another bodge job 😁 Does the job for me as a but doesn't really feel appropriate for Dink to employ imo.

```
    const regexHasJoined = /^(.*?)\s?has joined\./;
    var hasJoined = str.match(regexHasJoined);

    const regexHasLeft = /^(.*?)\s?has left\./;
    var hasLeft = str.match(regexHasLeft);
```

I've got one of those each for PBs, pets, raid loot, clogs, "has completed" (diary, CAs…), "has reached" (levels, XP milestones), and clue items…

>Instead you could store RSNs and associated title in a database as you receive `CLAN_CHAT`/`CLAN_GUEST_CHAT`

Yeah using the rank coming in via `CLAN_CHAT` to keep ranks up to date would be helpful to a degree, for sure. Otherwise a manual pull of that Clanmate Export data once a month or so isn't a big deal, just a bit of a faff. Would be nice if it were fully automated, but from what you've said it's not possible for dink to do it in a clean and "proper" way, so it's probably more appropriate to leave it off `CLAN_MESSAGE`s unless someone else comes along wanting the same thing.

Thanks again for your time btw :)

**Comment by iProdigy** [comment]
yeah there's too many cases for `CLAN_MESSAGE` for dink to add all those regexps - instead I'll only add `clanTitle` for the user joined `CLAN_MESSAGE` (and folks can simply cache name→title upon user joins depending on their use case)

sample `extra` object:
```json
{"type":"CLAN_MESSAGE","source":"","clanTitle":{"id":126,"name":"Queen"},"message":"Poki has joined."}
```

**Comment by tmgrhm** [comment]
That sounds great  
Sending the `id` with the text `name` for the rank will be useful to allow sorting by rank, cheers :)
