### ISSUE TITLE
Request: Ability to use a different webhook per category

### ISSUE THREAD

**Issue by CypherNL** [pajlads/DinkPlugin#77]
Our Discord channel uses multiple webhooks for different notifications (Clues for Clue Scrolls, Collection Log for collection logs etc.) so we can post them to different text channels on Discord. Our group uses many RuneLite plugins to make this happen.

Since this plugin has a lot of categories we could use and this plugin is actively maintained, i think it would be nice to have the option configure a webhook per category so we can replace other plugins in RuneLite with Dink and maybe use other features of this plugin without resorting to one webhook which means 1 text channel in Discord for everything.

**Comment by Felanbird** [comment]
I'm trying to think of what the correct approach would be for this. Maybe we make the webhook box into it's own section, with some form of "use all" that would default and follow the current behavior, but allow for this idea to be customized?

**Comment by iProdigy** [comment]
With the webhook per notifier approach, we could make the field hidden (so would have to edit config file directly) - this would avoid clutter but be an unfriendly user experience

**Comment by Felanbird** [comment]
I'm definitely not against this being a hidden feature, we could explain it in the webhook box, when empty.

**Comment by Mm2PL** [comment]
Hiding the configs and explaining editing the config file to users is more trouble than its worth IMO, we'd also have to handle edgecases like syncing with a goolag account. It would be way better to have this actually in the client UI.

Another idea could be just to have the user copy-paste the webhook into many text fields each for a notification type (probably in a closed-by-default category or something)

**Comment by pajlada** [comment]
Editing the config is going to be super jank since there isn't a plugin-specific config file

**Comment by iProdigy** [comment]
actually yeah, editing settings.properties directly also means explaining escape characters for the url, so let's scrap that idea

**Comment by iProdigy** [comment]
I agree with creating a separate closed-by-default ConfigSection for all of the webhook url overrides - to avoid a bunch of copypasta, we can just default to the primary webhook url if no override is specified
