### ISSUE TITLE
Loot from Unsired does not notify

### ISSUE THREAD

**Issue by jdanthdavis** [pajlads/DinkPlugin#86]
I received an Abyssal Dagger from using an Unsired but it did not post the loot. Loot threshold was set to 1M. If possible, when receiving an item with value from an Unsired it should notify the channel. Currently, bludgeon pieces have their individual worth posted in a clan chat when a player receives one.

**Comment by jdanthdavis** [comment]
It's worth noting the Abyssal Orphan may also be affected by this.

**Comment by iProdigy** [comment]
This is actually a problem with the upstream loot tracker in runelite (& we just consume their events for the loot notifier): https://github.com/runelite/runelite/issues/8478

(note: there is no unsired handling below)
* https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/game/LootManager.java
* https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java

**Comment by iProdigy** [comment]
@jdanthdavis Would you mind testing if #89 fixes this issue? (also I'd recommend lowering min loot value threshold while testing)

Steps:
0. Download `dinkplugin-shadow.zip` from https://github.com/pajlads/DinkPlugin/suites/9790836619/artifacts/470876555 (make sure you're logged into github)
1. Extract the zip, creating `dinkplugin-1.1.2-all.jar`
2. Open command prompt (or powershell or terminal) in the new folder with the jar (on windows, you can shift right click in the folder to get the option to open cmd/powershell)
3. Run: `java -ea -jar dinkplugin-1.1.2-all.jar`

**Comment by jdanthdavis** [comment]
I can! I'll keep you posted with my findings.

**Comment by Felanbird** [comment]
We went ahead and merged the fix attempt for this so testing it can be done easily.
It will be available in the normal plugin-hub version of Dink once runelite/plugin-hub#3723 is merged.
