### ISSUE TITLE
Death: 3 item icons posted on Death while no option to enable or disable this

### ISSUE THREAD

**Issue by CypherNL** [pajlads/DinkPlugin#90]
**Dink version:** 1.1.2
When posting a death, 3 icons of certain items are posted below the screenshot, this also happens when the screenshot feature is off.

![Dink deaths 3 icons](https://user-images.githubusercontent.com/11279045/206911931-c77c5284-f480-45b2-957e-b6729748165d.png)

There's no option on the Deaths section to disable or enable this.

**Comment by iProdigy** [comment]
I agree the icons of the 3 most valuable lost items need not be posted when screenshot is enabled.

Is it sufficient to only embed icons when screenshot of disabled, or is a separate config toggle desired?

**Comment by Felanbird** [comment]
Probably should just be a toggle similar to `Show Loot Icons` -> `Show Protected Item Icons`

**Comment by CypherNL** [comment]
> Probably should just be a toggle similar to `Show Loot Icons` -> `Show Protected Item Icons`

Something like that should be nice.
I didn't knew what these icons were for, maybe something adding like **Protected Items:** at the notification message by default should help that?

**Comment by iProdigy** [comment]
It's actually the valuable lost items (not protected): https://github.com/pajlads/DinkPlugin/blob/master/src/main/java/dinkplugin/notifiers/DeathNotifier.java#L104

**Comment by Felanbird** [comment]
> It's actually the valuable lost items (not protected): 

Ah, I forgot prims would be saved in a melee set, when I was looking for my own death notif.

If they aren't the protected items, I'm not really sure we care about displaying their icons in any scenario except PvP.
