### ISSUE TITLE
Only include screenshot on certain clue / drop value

### ISSUE THREAD

**Issue by zeroquinc** [pajlads/DinkPlugin#91]
Hi,

First of thanks for this plugin. It's by far the most complete by all others i've used.

Is it possible to show every clue / drop notification but only include a screenshot when the value is above x?

![RuneLite_aIOXkBtCNq](https://user-images.githubusercontent.com/39315068/207649209-4bd237fd-d214-403d-994b-41cb882e0b06.png)

Something like: Min Image Value

**Comment by Felanbird** [comment]
I've been thinking about whether or not I dislike this idea, but I think since only clues and loot have min value functionality, it should be fine to add.

**Comment by zeroquinc** [comment]
Thanks for adding this! Really appreciate it.

Excuse my ignorance, but how can I get this option in the RuneLite client now? Or do I have to wait untill you push a new release?

**Comment by Felanbird** [comment]
@zeroquinc You can click the ✔️ of the most recent commit, go to details, click Summary and download the `dinkplugin-shadow` to download the jar. or click this [direct link](https://github.com/pajlads/DinkPlugin/actions/runs/3743441650) `We will make this easier for the future.`
This can be used to start runelite with the plugin changes in said jar, by using the following command in any command prompt 
`java -ea -jar "path_to_jar_file"` so for me it would be `java -ea -jar "C:\users\felanbird\desktop\dink\dinkplugin-1.1.2-all.jar"`

images if you'd like to do it yourself:
![image](https://user-images.githubusercontent.com/41973452/209198347-a396f642-82a0-435a-aad2-507ded4ed8e7.png)
![image](https://user-images.githubusercontent.com/41973452/209198475-4b799d9f-8c66-4972-be1b-40cc7bf878f3.png)
![image](https://user-images.githubusercontent.com/41973452/209199055-3f2caab1-b32d-48b6-bd2c-1bc5aa6ab6fa.png)

**Comment by zeroquinc** [comment]
Thanks for the explanation! 

Do I have to do this once? It seems a bit of a hassle to start my RuneLite every time with that command.

I thought the way updates worked is that you pushed an update to the Plugin Hub and that I could see it automaticly?

**Comment by iProdigy** [comment]
We *will* push an update to the plugin hub, but it will be some time before the automatic update occurs because the folks at the hub take time to review our changes & we still have a couple PRs to merge before creating the hub update.

So, if you would like to enjoy the new features before the hub accepts it, you'll unfortunately have to use the more tedious shadow jar approach.

**Comment by zeroquinc** [comment]
Ah okay gotcha! I was a bit confused and thought I he meant to run that everytime.
I'll wait patiently for the hub update then! Thanks for all your work!

**Comment by iProdigy** [comment]
For the early shadow jar approach, yes you'd have to run the jar every time (but could create a batch file to save you the effort of typing the command every time)

**Comment by zeroquinc** [comment]
> For the early shadow jar approach, yes you'd have to run the jar every time (but could create a batch file to save you the effort of typing the command every time)

I understand yeah, I'm comfortable with doing these things but my other friends who use this plugin aren't sadly. I also do the settings for them so I'll wait for the plugin hub update so I can update all my friends in once. Thanks for the suggestion tho mate 👍

**Comment by Felanbird** [comment]
@zeroquinc We've released version [1.1.3](https://github.com/pajlads/DinkPlugin/releases/tag/v1.1.3) and opened a plugin-hub PR to go with it https://github.com/runelite/plugin-hub/pull/3723, so the changes will be available as soon as that PR is merged. 🙂

(also prodigy is looking into the discord embedding 😀)

**Comment by zeroquinc** [comment]
> @zeroquinc We've released version [1.1.3](https://github.com/pajlads/DinkPlugin/releases/tag/v1.1.3) and opened a plugin-hub PR to go with it [runelite/plugin-hub#3723](https://github.com/runelite/plugin-hub/pull/3723), so the changes will be available as soon as that PR is merged. 🙂
> 
> (also prodigy is looking into the discord embedding 😀)

Thats great news! Thanks a lot for the update and happy new year!
