### ISSUE TITLE
Diary Notifier sometimes does not send message

### ISSUE THREAD

**Issue by Felanbird** [pajlads/DinkPlugin#93]
Not an unexpected issue, it was to be expected Karamja would give us the hardest time, due to it's inconsistency in comparison to the other diaries.

![image](https://user-images.githubusercontent.com/41973452/208158429-582c003a-e19e-4ba7-967c-11c5bf234178.png)
![image](https://user-images.githubusercontent.com/41973452/208158510-a3b00734-d316-4613-abb1-7a9955dba461.png)
![image](https://user-images.githubusercontent.com/41973452/208158238-fb9b2f13-0162-4f86-8142-fa0b08ca7f31.png)

**Comment by iProdigy** [comment]
Would be useful to see if this is replicable after #94 & #96

**Comment by iProdigy** [comment]
Note: medium Karamja diary fired correctly for another dink user today

![image](https://user-images.githubusercontent.com/8106344/214121456-4b35b80d-68da-4907-883d-c039d3bbb1c8.png)

**Comment by pajlada** [comment]
I say we close this and use it as a reference in case the issue comes up again.
Thoughts @Felanbird @iProdigy
